// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every((MapEntry<Object?, Object?> entry) =>
            (b as Map<Object?, Object?>).containsKey(entry.key) &&
            _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}

/// Acquiring configuration for card-on-file / acquiring flows.
class KnAcquiringConfig {
  KnAcquiringConfig({
    required this.paymentAccountReference,
    required this.paymentAcquiringAccountId,
  });

  String paymentAccountReference;

  String paymentAcquiringAccountId;

  List<Object?> _toList() {
    return <Object?>[
      paymentAccountReference,
      paymentAcquiringAccountId,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnAcquiringConfig decode(Object result) {
    result as List<Object?>;
    return KnAcquiringConfig(
      paymentAccountReference: result[0]! as String,
      paymentAcquiringAccountId: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnAcquiringConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Configuration for creating a Klarna instance.
class KnConfiguration {
  KnConfiguration({
    required this.clientId,
    required this.appReturnUrl,
    this.accountId,
    this.locale,
    this.klarnaNetworkSessionToken,
    this.acquiringConfig,
  });

  String clientId;

  String appReturnUrl;

  String? accountId;

  String? locale;

  String? klarnaNetworkSessionToken;

  KnAcquiringConfig? acquiringConfig;

  List<Object?> _toList() {
    return <Object?>[
      clientId,
      appReturnUrl,
      accountId,
      locale,
      klarnaNetworkSessionToken,
      acquiringConfig,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnConfiguration decode(Object result) {
    result as List<Object?>;
    return KnConfiguration(
      clientId: result[0]! as String,
      appReturnUrl: result[1]! as String,
      accountId: result[2] as String?,
      locale: result[3] as String?,
      klarnaNetworkSessionToken: result[4] as String?,
      acquiringConfig: result[5] as KnAcquiringConfig?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnConfiguration || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Metadata identifying the Flutter integrator and optional originators.
class KnIntegrationMetadata {
  KnIntegrationMetadata({
    required this.integrator,
    this.originators,
  });

  KnIntegratorMetadata integrator;

  List<KnOriginatorMetadata>? originators;

  List<Object?> _toList() {
    return <Object?>[
      integrator,
      originators,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnIntegrationMetadata decode(Object result) {
    result as List<Object?>;
    return KnIntegrationMetadata(
      integrator: result[0]! as KnIntegratorMetadata,
      originators: (result[1] as List<Object?>?)?.cast<KnOriginatorMetadata>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnIntegrationMetadata || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Metadata for the top-level integration owner.
class KnIntegratorMetadata {
  KnIntegratorMetadata({
    required this.name,
    required this.sessionReference,
    this.moduleName,
    this.moduleVersion,
  });

  String name;

  String sessionReference;

  String? moduleName;

  String? moduleVersion;

  List<Object?> _toList() {
    return <Object?>[
      name,
      sessionReference,
      moduleName,
      moduleVersion,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnIntegratorMetadata decode(Object result) {
    result as List<Object?>;
    return KnIntegratorMetadata(
      name: result[0]! as String,
      sessionReference: result[1]! as String,
      moduleName: result[2] as String?,
      moduleVersion: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnIntegratorMetadata || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Metadata for an upstream module that originated the integration.
class KnOriginatorMetadata {
  KnOriginatorMetadata({
    required this.name,
    required this.sessionReference,
    this.moduleName,
    this.moduleVersion,
  });

  String name;

  String sessionReference;

  String? moduleName;

  String? moduleVersion;

  List<Object?> _toList() {
    return <Object?>[
      name,
      sessionReference,
      moduleName,
      moduleVersion,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnOriginatorMetadata decode(Object result) {
    result as List<Object?>;
    return KnOriginatorMetadata(
      name: result[0]! as String,
      sessionReference: result[1]! as String,
      moduleName: result[2] as String?,
      moduleVersion: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnOriginatorMetadata || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is KnAcquiringConfig) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is KnConfiguration) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is KnIntegrationMetadata) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is KnIntegratorMetadata) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is KnOriginatorMetadata) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return KnAcquiringConfig.decode(readValue(buffer)!);
      case 130:
        return KnConfiguration.decode(readValue(buffer)!);
      case 131:
        return KnIntegrationMetadata.decode(readValue(buffer)!);
      case 132:
        return KnIntegratorMetadata.decode(readValue(buffer)!);
      case 133:
        return KnOriginatorMetadata.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class KnCoreHostApi {
  /// Constructor for [KnCoreHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  KnCoreHostApi(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Create and store a Klarna instance for [instanceId].
  Future<void> initialize(
      String instanceId, KnConfiguration configuration) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.klarna_network_core.KnCoreHostApi.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[instanceId, configuration]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Fetch a Klarna Network session token.
  Future<String> getSessionToken(String instanceId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.klarna_network_core.KnCoreHostApi.getSessionToken$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[instanceId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  /// Clear the current session.
  Future<void> clearSession(String instanceId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.klarna_network_core.KnCoreHostApi.clearSession$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[instanceId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Attach integration metadata to an initialized Klarna instance.
  Future<void> setIntegrationMetadata(
      String instanceId, KnIntegrationMetadata metadata) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.klarna_network_core.KnCoreHostApi.setIntegrationMetadata$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[instanceId, metadata]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Handle a return URL (deep link) routed back into the app.
  Future<bool> handleReturnUrl(String url) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.klarna_network_core.KnCoreHostApi.handleReturnUrl$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[url]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Release the instance.
  Future<void> dispose(String instanceId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.klarna_network_core.KnCoreHostApi.dispose$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[instanceId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
