// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.klarna.mobile.sdk.klarna_network_core

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Acquiring configuration for card-on-file / acquiring flows.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class KnAcquiringConfig (
  val paymentAccountReference: String,
  val paymentAcquiringAccountId: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnAcquiringConfig {
      val paymentAccountReference = pigeonVar_list[0] as String
      val paymentAcquiringAccountId = pigeonVar_list[1] as String
      return KnAcquiringConfig(paymentAccountReference, paymentAcquiringAccountId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      paymentAccountReference,
      paymentAcquiringAccountId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnAcquiringConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for creating a Klarna instance.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class KnConfiguration (
  val clientId: String,
  val appReturnUrl: String,
  val accountId: String? = null,
  val locale: String? = null,
  val klarnaNetworkSessionToken: String? = null,
  val acquiringConfig: KnAcquiringConfig? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnConfiguration {
      val clientId = pigeonVar_list[0] as String
      val appReturnUrl = pigeonVar_list[1] as String
      val accountId = pigeonVar_list[2] as String?
      val locale = pigeonVar_list[3] as String?
      val klarnaNetworkSessionToken = pigeonVar_list[4] as String?
      val acquiringConfig = pigeonVar_list[5] as KnAcquiringConfig?
      return KnConfiguration(clientId, appReturnUrl, accountId, locale, klarnaNetworkSessionToken, acquiringConfig)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      clientId,
      appReturnUrl,
      accountId,
      locale,
      klarnaNetworkSessionToken,
      acquiringConfig,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnConfiguration) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Metadata identifying the Flutter integrator and optional originators.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class KnIntegrationMetadata (
  val integrator: KnIntegratorMetadata,
  val originators: List<KnOriginatorMetadata>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnIntegrationMetadata {
      val integrator = pigeonVar_list[0] as KnIntegratorMetadata
      val originators = pigeonVar_list[1] as List<KnOriginatorMetadata>?
      return KnIntegrationMetadata(integrator, originators)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      integrator,
      originators,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnIntegrationMetadata) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Metadata for the top-level integration owner.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class KnIntegratorMetadata (
  val name: String,
  val sessionReference: String,
  val moduleName: String? = null,
  val moduleVersion: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnIntegratorMetadata {
      val name = pigeonVar_list[0] as String
      val sessionReference = pigeonVar_list[1] as String
      val moduleName = pigeonVar_list[2] as String?
      val moduleVersion = pigeonVar_list[3] as String?
      return KnIntegratorMetadata(name, sessionReference, moduleName, moduleVersion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      sessionReference,
      moduleName,
      moduleVersion,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnIntegratorMetadata) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Metadata for an upstream module that originated the integration.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class KnOriginatorMetadata (
  val name: String,
  val sessionReference: String,
  val moduleName: String? = null,
  val moduleVersion: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnOriginatorMetadata {
      val name = pigeonVar_list[0] as String
      val sessionReference = pigeonVar_list[1] as String
      val moduleName = pigeonVar_list[2] as String?
      val moduleVersion = pigeonVar_list[3] as String?
      return KnOriginatorMetadata(name, sessionReference, moduleName, moduleVersion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      sessionReference,
      moduleName,
      moduleVersion,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnOriginatorMetadata) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnAcquiringConfig.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnConfiguration.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnIntegrationMetadata.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnIntegratorMetadata.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnOriginatorMetadata.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is KnAcquiringConfig -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is KnConfiguration -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is KnIntegrationMetadata -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is KnIntegratorMetadata -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is KnOriginatorMetadata -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface KnCoreHostApi {
  /** Create and store a Klarna instance for [instanceId]. */
  fun initialize(instanceId: String, configuration: KnConfiguration, callback: (Result<Unit>) -> Unit)
  /** Fetch a Klarna Network session token. */
  fun getSessionToken(instanceId: String, callback: (Result<String>) -> Unit)
  /** Clear the current session. */
  fun clearSession(instanceId: String, callback: (Result<Unit>) -> Unit)
  /** Attach integration metadata to an initialized Klarna instance. */
  fun setIntegrationMetadata(instanceId: String, metadata: KnIntegrationMetadata)
  /** Handle a return URL (deep link) routed back into the app. */
  fun handleReturnUrl(url: String, callback: (Result<Boolean>) -> Unit)
  /** Release the instance. */
  fun dispose(instanceId: String)

  companion object {
    /** The codec used by KnCoreHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `KnCoreHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: KnCoreHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.klarna_network_core.KnCoreHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val instanceIdArg = args[0] as String
            val configurationArg = args[1] as KnConfiguration
            api.initialize(instanceIdArg, configurationArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.klarna_network_core.KnCoreHostApi.getSessionToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val instanceIdArg = args[0] as String
            api.getSessionToken(instanceIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.klarna_network_core.KnCoreHostApi.clearSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val instanceIdArg = args[0] as String
            api.clearSession(instanceIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.klarna_network_core.KnCoreHostApi.setIntegrationMetadata$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val instanceIdArg = args[0] as String
            val metadataArg = args[1] as KnIntegrationMetadata
            val wrapped: List<Any?> = try {
              api.setIntegrationMetadata(instanceIdArg, metadataArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.klarna_network_core.KnCoreHostApi.handleReturnUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.handleReturnUrl(urlArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.klarna_network_core.KnCoreHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val instanceIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.dispose(instanceIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
