// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Acquiring configuration for card-on-file / acquiring flows.
///
/// Generated class from Pigeon that represents data sent in messages.
struct KnAcquiringConfig: Hashable {
  var paymentAccountReference: String
  var paymentAcquiringAccountId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnAcquiringConfig? {
    let paymentAccountReference = pigeonVar_list[0] as! String
    let paymentAcquiringAccountId = pigeonVar_list[1] as! String

    return KnAcquiringConfig(
      paymentAccountReference: paymentAccountReference,
      paymentAcquiringAccountId: paymentAcquiringAccountId
    )
  }
  func toList() -> [Any?] {
    return [
      paymentAccountReference,
      paymentAcquiringAccountId,
    ]
  }
  static func == (lhs: KnAcquiringConfig, rhs: KnAcquiringConfig) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Configuration for creating a Klarna instance.
///
/// Generated class from Pigeon that represents data sent in messages.
struct KnConfiguration: Hashable {
  var clientId: String
  var appReturnUrl: String
  var accountId: String? = nil
  var locale: String? = nil
  var klarnaNetworkSessionToken: String? = nil
  var acquiringConfig: KnAcquiringConfig? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnConfiguration? {
    let clientId = pigeonVar_list[0] as! String
    let appReturnUrl = pigeonVar_list[1] as! String
    let accountId: String? = nilOrValue(pigeonVar_list[2])
    let locale: String? = nilOrValue(pigeonVar_list[3])
    let klarnaNetworkSessionToken: String? = nilOrValue(pigeonVar_list[4])
    let acquiringConfig: KnAcquiringConfig? = nilOrValue(pigeonVar_list[5])

    return KnConfiguration(
      clientId: clientId,
      appReturnUrl: appReturnUrl,
      accountId: accountId,
      locale: locale,
      klarnaNetworkSessionToken: klarnaNetworkSessionToken,
      acquiringConfig: acquiringConfig
    )
  }
  func toList() -> [Any?] {
    return [
      clientId,
      appReturnUrl,
      accountId,
      locale,
      klarnaNetworkSessionToken,
      acquiringConfig,
    ]
  }
  static func == (lhs: KnConfiguration, rhs: KnConfiguration) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Metadata identifying the Flutter integrator and optional originators.
///
/// Generated class from Pigeon that represents data sent in messages.
struct KnIntegrationMetadata: Hashable {
  var integrator: KnIntegratorMetadata
  var originators: [KnOriginatorMetadata]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnIntegrationMetadata? {
    let integrator = pigeonVar_list[0] as! KnIntegratorMetadata
    let originators: [KnOriginatorMetadata]? = nilOrValue(pigeonVar_list[1])

    return KnIntegrationMetadata(
      integrator: integrator,
      originators: originators
    )
  }
  func toList() -> [Any?] {
    return [
      integrator,
      originators,
    ]
  }
  static func == (lhs: KnIntegrationMetadata, rhs: KnIntegrationMetadata) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Metadata for the top-level integration owner.
///
/// Generated class from Pigeon that represents data sent in messages.
struct KnIntegratorMetadata: Hashable {
  var name: String
  var sessionReference: String
  var moduleName: String? = nil
  var moduleVersion: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnIntegratorMetadata? {
    let name = pigeonVar_list[0] as! String
    let sessionReference = pigeonVar_list[1] as! String
    let moduleName: String? = nilOrValue(pigeonVar_list[2])
    let moduleVersion: String? = nilOrValue(pigeonVar_list[3])

    return KnIntegratorMetadata(
      name: name,
      sessionReference: sessionReference,
      moduleName: moduleName,
      moduleVersion: moduleVersion
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      sessionReference,
      moduleName,
      moduleVersion,
    ]
  }
  static func == (lhs: KnIntegratorMetadata, rhs: KnIntegratorMetadata) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Metadata for an upstream module that originated the integration.
///
/// Generated class from Pigeon that represents data sent in messages.
struct KnOriginatorMetadata: Hashable {
  var name: String
  var sessionReference: String
  var moduleName: String? = nil
  var moduleVersion: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnOriginatorMetadata? {
    let name = pigeonVar_list[0] as! String
    let sessionReference = pigeonVar_list[1] as! String
    let moduleName: String? = nilOrValue(pigeonVar_list[2])
    let moduleVersion: String? = nilOrValue(pigeonVar_list[3])

    return KnOriginatorMetadata(
      name: name,
      sessionReference: sessionReference,
      moduleName: moduleName,
      moduleVersion: moduleVersion
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      sessionReference,
      moduleName,
      moduleVersion,
    ]
  }
  static func == (lhs: KnOriginatorMetadata, rhs: KnOriginatorMetadata) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return KnAcquiringConfig.fromList(self.readValue() as! [Any?])
    case 130:
      return KnConfiguration.fromList(self.readValue() as! [Any?])
    case 131:
      return KnIntegrationMetadata.fromList(self.readValue() as! [Any?])
    case 132:
      return KnIntegratorMetadata.fromList(self.readValue() as! [Any?])
    case 133:
      return KnOriginatorMetadata.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? KnAcquiringConfig {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? KnConfiguration {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? KnIntegrationMetadata {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? KnIntegratorMetadata {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? KnOriginatorMetadata {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol KnCoreHostApi {
  /// Create and store a Klarna instance for [instanceId].
  func initialize(instanceId: String, configuration: KnConfiguration, completion: @escaping (Result<Void, Error>) -> Void)
  /// Fetch a Klarna Network session token.
  func getSessionToken(instanceId: String, completion: @escaping (Result<String, Error>) -> Void)
  /// Clear the current session.
  func clearSession(instanceId: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Attach integration metadata to an initialized Klarna instance.
  func setIntegrationMetadata(instanceId: String, metadata: KnIntegrationMetadata) throws
  /// Handle a return URL (deep link) routed back into the app.
  func handleReturnUrl(url: String, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Release the instance.
  func dispose(instanceId: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class KnCoreHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `KnCoreHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: KnCoreHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Create and store a Klarna instance for [instanceId].
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.klarna_network_core.KnCoreHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let instanceIdArg = args[0] as! String
        let configurationArg = args[1] as! KnConfiguration
        api.initialize(instanceId: instanceIdArg, configuration: configurationArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Fetch a Klarna Network session token.
    let getSessionTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.klarna_network_core.KnCoreHostApi.getSessionToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSessionTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let instanceIdArg = args[0] as! String
        api.getSessionToken(instanceId: instanceIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getSessionTokenChannel.setMessageHandler(nil)
    }
    /// Clear the current session.
    let clearSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.klarna_network_core.KnCoreHostApi.clearSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let instanceIdArg = args[0] as! String
        api.clearSession(instanceId: instanceIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearSessionChannel.setMessageHandler(nil)
    }
    /// Attach integration metadata to an initialized Klarna instance.
    let setIntegrationMetadataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.klarna_network_core.KnCoreHostApi.setIntegrationMetadata\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setIntegrationMetadataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let instanceIdArg = args[0] as! String
        let metadataArg = args[1] as! KnIntegrationMetadata
        do {
          try api.setIntegrationMetadata(instanceId: instanceIdArg, metadata: metadataArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setIntegrationMetadataChannel.setMessageHandler(nil)
    }
    /// Handle a return URL (deep link) routed back into the app.
    let handleReturnUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.klarna_network_core.KnCoreHostApi.handleReturnUrl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      handleReturnUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        api.handleReturnUrl(url: urlArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      handleReturnUrlChannel.setMessageHandler(nil)
    }
    /// Release the instance.
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.klarna_network_core.KnCoreHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let instanceIdArg = args[0] as! String
        do {
          try api.dispose(instanceId: instanceIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
