// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.klarna.mobile.sdk.klarna_network_payment

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class KnPaymentRequestState(val raw: Int) {
  SUBMITTED(0),
  IN_PROGRESS(1),
  COMPLETED(2),
  EXPIRED(3),
  CANCELED(4),
  DECLINED(5);

  companion object {
    fun ofRaw(raw: Int): KnPaymentRequestState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class KnPaymentRequestStateReason(val raw: Int) {
  PARTNER_CANCELED(0),
  PAYMENT_REQUEST_SUBMITTED(1),
  PURCHASE_FLOW_ABORTED(2),
  TECHNICAL_ERROR(3),
  PAYMENT_DECLINED(4);

  companion object {
    fun ofRaw(raw: Int): KnPaymentRequestStateReason? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class KnCollectCustomerProfileType(val raw: Int) {
  BILLING_ADDRESS(0),
  COUNTRY(1),
  DATE_OF_BIRTH(2),
  EMAIL(3),
  LOCALE(4),
  NAME(5),
  NATIONAL_IDENTIFICATION(6),
  PHONE(7);

  companion object {
    fun ofRaw(raw: Int): KnCollectCustomerProfileType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class KnRequestCustomerTokenScope(val raw: Int) {
  CUSTOMER_LOGIN(0),
  PAYMENT_CUSTOMER_NOT_PRESENT(1),
  PAYMENT_CUSTOMER_PRESENT(2);

  companion object {
    fun ofRaw(raw: Int): KnRequestCustomerTokenScope? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class KnShippingConfigMode(val raw: Int) {
  EDITABLE(0);

  companion object {
    fun ofRaw(raw: Int): KnShippingConfigMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class KnShippingType(val raw: Int) {
  DIGITAL_DOWNLOAD(0),
  DIGITAL_EMAIL(1),
  DIGITAL_OTHER(2),
  PHYSICAL_OTHER(3),
  PICKUP_BOX(4),
  PICKUP_POINT(5),
  PICKUP_STORE(6),
  PICKUP_WAREHOUSE(7),
  TO_CURB(8),
  TO_DOOR(9),
  TO_MAILBOX(10);

  companion object {
    fun ofRaw(raw: Int): KnShippingType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class KnShippingTypeAttribute(val raw: Int) {
  CONTACTLESS_DELIVERY(0),
  EXPRESS(1),
  IDENTIFICATION_REQUIRED(2),
  LEAVE_AT_CURB(3),
  LEAVE_AT_DOOR(4),
  LEAVE_WITH_NEIGHBOUR(5),
  SIGNATURE_REQUIRED(6),
  TRACKED(7),
  UNTRACKED(8);

  companion object {
    fun ofRaw(raw: Int): KnShippingTypeAttribute? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class KnInterval(val raw: Int) {
  DAY(0),
  WEEK(1),
  MONTH(2),
  YEAR(3);

  companion object {
    fun ofRaw(raw: Int): KnInterval? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class KnFreeTrial(val raw: Int) {
  ACTIVE(0),
  INACTIVE(1);

  companion object {
    fun ofRaw(raw: Int): KnFreeTrial? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class KnPresentationIntent(val raw: Int) {
  PAY(0),
  SUBSCRIBE(1),
  ADD_TO_WALLET(2);

  companion object {
    fun ofRaw(raw: Int): KnPresentationIntent? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class KnPresentationInstruction(val raw: Int) {
  SHOW_KLARNA(0),
  PRESELECT_KLARNA(1),
  SHOW_ONLY_KLARNA(2);

  companion object {
    fun ofRaw(raw: Int): KnPresentationInstruction? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class KnPresentationPaymentStatus(val raw: Int) {
  PENDING_PARTNER_AUTHORIZATION(0),
  REQUIRES_CUSTOMER_ACTION(1);

  companion object {
    fun ofRaw(raw: Int): KnPresentationPaymentStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class KnPresentationImageAlignment(val raw: Int) {
  LEFT(0),
  RIGHT(1);

  companion object {
    fun ofRaw(raw: Int): KnPresentationImageAlignment? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class KnPresentationTextPartStyle(val raw: Int) {
  BOLD(0),
  ITALIC(1),
  UNDERLINE(2);

  companion object {
    fun ofRaw(raw: Int): KnPresentationTextPartStyle? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class KnPresentationTextPartLinkContext(val raw: Int) {
  AUTH(0),
  INFO(1);

  companion object {
    fun ofRaw(raw: Int): KnPresentationTextPartLinkContext? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnPaymentRequestData (
  val currency: String,
  val amount: Long,
  val paymentOptionId: String? = null,
  val paymentRequestReference: String? = null,
  val requestCustomerToken: KnRequestCustomerToken? = null,
  val shippingConfig: KnShippingConfig? = null,
  val collectCustomerProfile: List<KnCollectCustomerProfileType?>? = null,
  val supplementaryPurchaseData: KnSupplementaryPurchaseData? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnPaymentRequestData {
      val currency = pigeonVar_list[0] as String
      val amount = pigeonVar_list[1] as Long
      val paymentOptionId = pigeonVar_list[2] as String?
      val paymentRequestReference = pigeonVar_list[3] as String?
      val requestCustomerToken = pigeonVar_list[4] as KnRequestCustomerToken?
      val shippingConfig = pigeonVar_list[5] as KnShippingConfig?
      val collectCustomerProfile = pigeonVar_list[6] as List<KnCollectCustomerProfileType?>?
      val supplementaryPurchaseData = pigeonVar_list[7] as KnSupplementaryPurchaseData?
      return KnPaymentRequestData(currency, amount, paymentOptionId, paymentRequestReference, requestCustomerToken, shippingConfig, collectCustomerProfile, supplementaryPurchaseData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      currency,
      amount,
      paymentOptionId,
      paymentRequestReference,
      requestCustomerToken,
      shippingConfig,
      collectCustomerProfile,
      supplementaryPurchaseData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnPaymentRequestData) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnPaymentRequest (
  val paymentRequestId: String,
  val state: KnPaymentRequestState,
  val previousState: KnPaymentRequestState? = null,
  val stateReason: KnPaymentRequestStateReason? = null,
  val paymentRequestReference: String? = null,
  val stateContext: KnPaymentRequestStateContext? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnPaymentRequest {
      val paymentRequestId = pigeonVar_list[0] as String
      val state = pigeonVar_list[1] as KnPaymentRequestState
      val previousState = pigeonVar_list[2] as KnPaymentRequestState?
      val stateReason = pigeonVar_list[3] as KnPaymentRequestStateReason?
      val paymentRequestReference = pigeonVar_list[4] as String?
      val stateContext = pigeonVar_list[5] as KnPaymentRequestStateContext?
      return KnPaymentRequest(paymentRequestId, state, previousState, stateReason, paymentRequestReference, stateContext)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      paymentRequestId,
      state,
      previousState,
      stateReason,
      paymentRequestReference,
      stateContext,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnPaymentRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnRequestCustomerToken (
  val scopes: List<KnRequestCustomerTokenScope?>,
  val customerTokenReference: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnRequestCustomerToken {
      val scopes = pigeonVar_list[0] as List<KnRequestCustomerTokenScope?>
      val customerTokenReference = pigeonVar_list[1] as String?
      return KnRequestCustomerToken(scopes, customerTokenReference)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      scopes,
      customerTokenReference,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnRequestCustomerToken) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnShippingConfig (
  val mode: KnShippingConfigMode,
  val supportedCountries: List<String>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnShippingConfig {
      val mode = pigeonVar_list[0] as KnShippingConfigMode
      val supportedCountries = pigeonVar_list[1] as List<String>?
      return KnShippingConfig(mode, supportedCountries)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mode,
      supportedCountries,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnShippingConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnSupplementaryPurchaseData (
  val customer: KnPartnerCustomer? = null,
  val lineItems: List<KnLineItem>? = null,
  val purchaseReference: String? = null,
  val shipping: List<KnShipping>? = null,
  val ondemandService: KnOndemandService? = null,
  val subscriptions: List<KnSubscription>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnSupplementaryPurchaseData {
      val customer = pigeonVar_list[0] as KnPartnerCustomer?
      val lineItems = pigeonVar_list[1] as List<KnLineItem>?
      val purchaseReference = pigeonVar_list[2] as String?
      val shipping = pigeonVar_list[3] as List<KnShipping>?
      val ondemandService = pigeonVar_list[4] as KnOndemandService?
      val subscriptions = pigeonVar_list[5] as List<KnSubscription>?
      return KnSupplementaryPurchaseData(customer, lineItems, purchaseReference, shipping, ondemandService, subscriptions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      customer,
      lineItems,
      purchaseReference,
      shipping,
      ondemandService,
      subscriptions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnSupplementaryPurchaseData) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnPartnerCustomer (
  val address: KnAddress? = null,
  val email: String? = null,
  val familyName: String? = null,
  val givenName: String? = null,
  val phone: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnPartnerCustomer {
      val address = pigeonVar_list[0] as KnAddress?
      val email = pigeonVar_list[1] as String?
      val familyName = pigeonVar_list[2] as String?
      val givenName = pigeonVar_list[3] as String?
      val phone = pigeonVar_list[4] as String?
      return KnPartnerCustomer(address, email, familyName, givenName, phone)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      address,
      email,
      familyName,
      givenName,
      phone,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnPartnerCustomer) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnAddress (
  val streetAddress: String? = null,
  val streetAddress2: String? = null,
  val city: String? = null,
  val region: String? = null,
  val postalCode: String? = null,
  val country: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnAddress {
      val streetAddress = pigeonVar_list[0] as String?
      val streetAddress2 = pigeonVar_list[1] as String?
      val city = pigeonVar_list[2] as String?
      val region = pigeonVar_list[3] as String?
      val postalCode = pigeonVar_list[4] as String?
      val country = pigeonVar_list[5] as String?
      return KnAddress(streetAddress, streetAddress2, city, region, postalCode, country)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      streetAddress,
      streetAddress2,
      city,
      region,
      postalCode,
      country,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnAddress) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnLineItem (
  val name: String,
  val quantity: Long,
  val totalAmount: Long,
  val currency: String? = null,
  val imageUrl: String? = null,
  val productIdentifier: String? = null,
  val productUrl: String? = null,
  val lineItemReference: String? = null,
  val shippingReference: String? = null,
  val subscriptionReference: String? = null,
  val totalTaxAmount: Long? = null,
  val unitPrice: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnLineItem {
      val name = pigeonVar_list[0] as String
      val quantity = pigeonVar_list[1] as Long
      val totalAmount = pigeonVar_list[2] as Long
      val currency = pigeonVar_list[3] as String?
      val imageUrl = pigeonVar_list[4] as String?
      val productIdentifier = pigeonVar_list[5] as String?
      val productUrl = pigeonVar_list[6] as String?
      val lineItemReference = pigeonVar_list[7] as String?
      val shippingReference = pigeonVar_list[8] as String?
      val subscriptionReference = pigeonVar_list[9] as String?
      val totalTaxAmount = pigeonVar_list[10] as Long?
      val unitPrice = pigeonVar_list[11] as Long?
      return KnLineItem(name, quantity, totalAmount, currency, imageUrl, productIdentifier, productUrl, lineItemReference, shippingReference, subscriptionReference, totalTaxAmount, unitPrice)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      quantity,
      totalAmount,
      currency,
      imageUrl,
      productIdentifier,
      productUrl,
      lineItemReference,
      shippingReference,
      subscriptionReference,
      totalTaxAmount,
      unitPrice,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnLineItem) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnShipping (
  val address: KnAddress? = null,
  val recipient: KnShippingRecipient? = null,
  val shippingOption: KnShippingOption? = null,
  val shippingReference: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnShipping {
      val address = pigeonVar_list[0] as KnAddress?
      val recipient = pigeonVar_list[1] as KnShippingRecipient?
      val shippingOption = pigeonVar_list[2] as KnShippingOption?
      val shippingReference = pigeonVar_list[3] as String?
      return KnShipping(address, recipient, shippingOption, shippingReference)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      address,
      recipient,
      shippingOption,
      shippingReference,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnShipping) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnShippingRecipient (
  val familyName: String,
  val givenName: String,
  val attention: String? = null,
  val email: String? = null,
  val phone: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnShippingRecipient {
      val familyName = pigeonVar_list[0] as String
      val givenName = pigeonVar_list[1] as String
      val attention = pigeonVar_list[2] as String?
      val email = pigeonVar_list[3] as String?
      val phone = pigeonVar_list[4] as String?
      return KnShippingRecipient(familyName, givenName, attention, email, phone)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      familyName,
      givenName,
      attention,
      email,
      phone,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnShippingRecipient) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnShippingOption (
  val shippingType: KnShippingType,
  val shippingCarrier: String? = null,
  val shippingTypeAttributes: List<KnShippingTypeAttribute?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnShippingOption {
      val shippingType = pigeonVar_list[0] as KnShippingType
      val shippingCarrier = pigeonVar_list[1] as String?
      val shippingTypeAttributes = pigeonVar_list[2] as List<KnShippingTypeAttribute?>?
      return KnShippingOption(shippingType, shippingCarrier, shippingTypeAttributes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      shippingType,
      shippingCarrier,
      shippingTypeAttributes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnShippingOption) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnOndemandService (
  val currency: String? = null,
  val averageAmount: Long? = null,
  val minimumAmount: Long? = null,
  val maximumAmount: Long? = null,
  val purchaseInterval: KnInterval? = null,
  val purchaseIntervalFrequency: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnOndemandService {
      val currency = pigeonVar_list[0] as String?
      val averageAmount = pigeonVar_list[1] as Long?
      val minimumAmount = pigeonVar_list[2] as Long?
      val maximumAmount = pigeonVar_list[3] as Long?
      val purchaseInterval = pigeonVar_list[4] as KnInterval?
      val purchaseIntervalFrequency = pigeonVar_list[5] as Long?
      return KnOndemandService(currency, averageAmount, minimumAmount, maximumAmount, purchaseInterval, purchaseIntervalFrequency)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      currency,
      averageAmount,
      minimumAmount,
      maximumAmount,
      purchaseInterval,
      purchaseIntervalFrequency,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnOndemandService) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnSubscription (
  val subscriptionReference: String,
  val name: String? = null,
  val freeTrial: KnFreeTrial? = null,
  val billingPlans: List<KnBillingPlan>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnSubscription {
      val subscriptionReference = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String?
      val freeTrial = pigeonVar_list[2] as KnFreeTrial?
      val billingPlans = pigeonVar_list[3] as List<KnBillingPlan>?
      return KnSubscription(subscriptionReference, name, freeTrial, billingPlans)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      subscriptionReference,
      name,
      freeTrial,
      billingPlans,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnSubscription) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnBillingPlan (
  val billingAmount: Long,
  val from: String,
  val interval: KnInterval,
  val intervalFrequency: Long,
  val currency: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnBillingPlan {
      val billingAmount = pigeonVar_list[0] as Long
      val from = pigeonVar_list[1] as String
      val interval = pigeonVar_list[2] as KnInterval
      val intervalFrequency = pigeonVar_list[3] as Long
      val currency = pigeonVar_list[4] as String?
      return KnBillingPlan(billingAmount, from, interval, intervalFrequency, currency)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      billingAmount,
      from,
      interval,
      intervalFrequency,
      currency,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnBillingPlan) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnPaymentRequestStateContext (
  val klarnaNetworkSessionToken: String? = null,
  val klarnaCustomer: KnCustomer? = null,
  val shipping: KnShipping? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnPaymentRequestStateContext {
      val klarnaNetworkSessionToken = pigeonVar_list[0] as String?
      val klarnaCustomer = pigeonVar_list[1] as KnCustomer?
      val shipping = pigeonVar_list[2] as KnShipping?
      return KnPaymentRequestStateContext(klarnaNetworkSessionToken, klarnaCustomer, shipping)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      klarnaNetworkSessionToken,
      klarnaCustomer,
      shipping,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnPaymentRequestStateContext) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnCustomer (
  val customerToken: String? = null,
  val customerTokenReference: String? = null,
  val customerProfile: KnCustomerProfile? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnCustomer {
      val customerToken = pigeonVar_list[0] as String?
      val customerTokenReference = pigeonVar_list[1] as String?
      val customerProfile = pigeonVar_list[2] as KnCustomerProfile?
      return KnCustomer(customerToken, customerTokenReference, customerProfile)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      customerToken,
      customerTokenReference,
      customerProfile,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnCustomer) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnCustomerProfile (
  val address: KnAddress? = null,
  val customerId: String? = null,
  val country: String? = null,
  val email: String? = null,
  val emailVerified: Boolean? = null,
  val familyName: String? = null,
  val givenName: String? = null,
  val locale: String? = null,
  val phone: String? = null,
  val phoneVerified: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnCustomerProfile {
      val address = pigeonVar_list[0] as KnAddress?
      val customerId = pigeonVar_list[1] as String?
      val country = pigeonVar_list[2] as String?
      val email = pigeonVar_list[3] as String?
      val emailVerified = pigeonVar_list[4] as Boolean?
      val familyName = pigeonVar_list[5] as String?
      val givenName = pigeonVar_list[6] as String?
      val locale = pigeonVar_list[7] as String?
      val phone = pigeonVar_list[8] as String?
      val phoneVerified = pigeonVar_list[9] as Boolean?
      return KnCustomerProfile(address, customerId, country, email, emailVerified, familyName, givenName, locale, phone, phoneVerified)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      address,
      customerId,
      country,
      email,
      emailVerified,
      familyName,
      givenName,
      locale,
      phone,
      phoneVerified,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnCustomerProfile) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnPresentationData (
  val currency: String,
  val amount: Long,
  val intent: KnPresentationIntent? = null,
  val paymentProgramEnablementCodes: List<String>? = null,
  val subscriptionBillingInterval: KnInterval? = null,
  val subscriptionBillingIntervalFrequency: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnPresentationData {
      val currency = pigeonVar_list[0] as String
      val amount = pigeonVar_list[1] as Long
      val intent = pigeonVar_list[2] as KnPresentationIntent?
      val paymentProgramEnablementCodes = pigeonVar_list[3] as List<String>?
      val subscriptionBillingInterval = pigeonVar_list[4] as KnInterval?
      val subscriptionBillingIntervalFrequency = pigeonVar_list[5] as Long?
      return KnPresentationData(currency, amount, intent, paymentProgramEnablementCodes, subscriptionBillingInterval, subscriptionBillingIntervalFrequency)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      currency,
      amount,
      intent,
      paymentProgramEnablementCodes,
      subscriptionBillingInterval,
      subscriptionBillingIntervalFrequency,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnPresentationData) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnPresentationContent (
  val instruction: KnPresentationInstruction,
  val paymentStatus: KnPresentationPaymentStatus? = null,
  val paymentOption: KnPresentationPaymentOption? = null,
  val savedPaymentOption: KnPresentationPaymentOption? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnPresentationContent {
      val instruction = pigeonVar_list[0] as KnPresentationInstruction
      val paymentStatus = pigeonVar_list[1] as KnPresentationPaymentStatus?
      val paymentOption = pigeonVar_list[2] as KnPresentationPaymentOption?
      val savedPaymentOption = pigeonVar_list[3] as KnPresentationPaymentOption?
      return KnPresentationContent(instruction, paymentStatus, paymentOption, savedPaymentOption)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      instruction,
      paymentStatus,
      paymentOption,
      savedPaymentOption,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnPresentationContent) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnPresentationPaymentOption (
  val paymentOptionId: String,
  val header: KnPresentationText? = null,
  val badge: KnPresentationText? = null,
  val subheader: KnPresentationText? = null,
  val message: KnPresentationText? = null,
  val terms: KnPresentationText? = null,
  val paymentButton: KnPresentationPaymentButton? = null,
  val icon: KnPresentationIcon? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnPresentationPaymentOption {
      val paymentOptionId = pigeonVar_list[0] as String
      val header = pigeonVar_list[1] as KnPresentationText?
      val badge = pigeonVar_list[2] as KnPresentationText?
      val subheader = pigeonVar_list[3] as KnPresentationText?
      val message = pigeonVar_list[4] as KnPresentationText?
      val terms = pigeonVar_list[5] as KnPresentationText?
      val paymentButton = pigeonVar_list[6] as KnPresentationPaymentButton?
      val icon = pigeonVar_list[7] as KnPresentationIcon?
      return KnPresentationPaymentOption(paymentOptionId, header, badge, subheader, message, terms, paymentButton, icon)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      paymentOptionId,
      header,
      badge,
      subheader,
      message,
      terms,
      paymentButton,
      icon,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnPresentationPaymentOption) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnPresentationText (
  val type: String,
  val text: String? = null,
  val parts: List<KnPresentationTextPart>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnPresentationText {
      val type = pigeonVar_list[0] as String
      val text = pigeonVar_list[1] as String?
      val parts = pigeonVar_list[2] as List<KnPresentationTextPart>?
      return KnPresentationText(type, text, parts)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      text,
      parts,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnPresentationText) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnPresentationTextPart (
  val type: String,
  val text: String,
  val url: String? = null,
  val context: KnPresentationTextPartLinkContext? = null,
  val styles: List<KnPresentationTextPartStyle?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnPresentationTextPart {
      val type = pigeonVar_list[0] as String
      val text = pigeonVar_list[1] as String
      val url = pigeonVar_list[2] as String?
      val context = pigeonVar_list[3] as KnPresentationTextPartLinkContext?
      val styles = pigeonVar_list[4] as List<KnPresentationTextPartStyle?>?
      return KnPresentationTextPart(type, text, url, context, styles)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      text,
      url,
      context,
      styles,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnPresentationTextPart) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnPresentationPaymentButton (
  val text: String,
  val imageUrl: String? = null,
  val imageAlignment: KnPresentationImageAlignment? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnPresentationPaymentButton {
      val text = pigeonVar_list[0] as String
      val imageUrl = pigeonVar_list[1] as String?
      val imageAlignment = pigeonVar_list[2] as KnPresentationImageAlignment?
      return KnPresentationPaymentButton(text, imageUrl, imageAlignment)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      text,
      imageUrl,
      imageAlignment,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnPresentationPaymentButton) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KnPresentationIcon (
  val alt: String? = null,
  val badgeImageUrl: String? = null,
  val rectangleImageUrl: String? = null,
  val squareImageUrl: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KnPresentationIcon {
      val alt = pigeonVar_list[0] as String?
      val badgeImageUrl = pigeonVar_list[1] as String?
      val rectangleImageUrl = pigeonVar_list[2] as String?
      val squareImageUrl = pigeonVar_list[3] as String?
      return KnPresentationIcon(alt, badgeImageUrl, rectangleImageUrl, squareImageUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      alt,
      badgeImageUrl,
      rectangleImageUrl,
      squareImageUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KnPresentationIcon) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KnPaymentRequestState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KnPaymentRequestStateReason.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KnCollectCustomerProfileType.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KnRequestCustomerTokenScope.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KnShippingConfigMode.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KnShippingType.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KnShippingTypeAttribute.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KnInterval.ofRaw(it.toInt())
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KnFreeTrial.ofRaw(it.toInt())
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KnPresentationIntent.ofRaw(it.toInt())
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KnPresentationInstruction.ofRaw(it.toInt())
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KnPresentationPaymentStatus.ofRaw(it.toInt())
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KnPresentationImageAlignment.ofRaw(it.toInt())
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KnPresentationTextPartStyle.ofRaw(it.toInt())
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KnPresentationTextPartLinkContext.ofRaw(it.toInt())
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnPaymentRequestData.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnPaymentRequest.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnRequestCustomerToken.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnShippingConfig.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnSupplementaryPurchaseData.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnPartnerCustomer.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnAddress.fromList(it)
        }
      }
      151.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnLineItem.fromList(it)
        }
      }
      152.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnShipping.fromList(it)
        }
      }
      153.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnShippingRecipient.fromList(it)
        }
      }
      154.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnShippingOption.fromList(it)
        }
      }
      155.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnOndemandService.fromList(it)
        }
      }
      156.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnSubscription.fromList(it)
        }
      }
      157.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnBillingPlan.fromList(it)
        }
      }
      158.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnPaymentRequestStateContext.fromList(it)
        }
      }
      159.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnCustomer.fromList(it)
        }
      }
      160.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnCustomerProfile.fromList(it)
        }
      }
      161.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnPresentationData.fromList(it)
        }
      }
      162.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnPresentationContent.fromList(it)
        }
      }
      163.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnPresentationPaymentOption.fromList(it)
        }
      }
      164.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnPresentationText.fromList(it)
        }
      }
      165.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnPresentationTextPart.fromList(it)
        }
      }
      166.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnPresentationPaymentButton.fromList(it)
        }
      }
      167.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KnPresentationIcon.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is KnPaymentRequestState -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is KnPaymentRequestStateReason -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is KnCollectCustomerProfileType -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is KnRequestCustomerTokenScope -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is KnShippingConfigMode -> {
        stream.write(133)
        writeValue(stream, value.raw)
      }
      is KnShippingType -> {
        stream.write(134)
        writeValue(stream, value.raw)
      }
      is KnShippingTypeAttribute -> {
        stream.write(135)
        writeValue(stream, value.raw)
      }
      is KnInterval -> {
        stream.write(136)
        writeValue(stream, value.raw)
      }
      is KnFreeTrial -> {
        stream.write(137)
        writeValue(stream, value.raw)
      }
      is KnPresentationIntent -> {
        stream.write(138)
        writeValue(stream, value.raw)
      }
      is KnPresentationInstruction -> {
        stream.write(139)
        writeValue(stream, value.raw)
      }
      is KnPresentationPaymentStatus -> {
        stream.write(140)
        writeValue(stream, value.raw)
      }
      is KnPresentationImageAlignment -> {
        stream.write(141)
        writeValue(stream, value.raw)
      }
      is KnPresentationTextPartStyle -> {
        stream.write(142)
        writeValue(stream, value.raw)
      }
      is KnPresentationTextPartLinkContext -> {
        stream.write(143)
        writeValue(stream, value.raw)
      }
      is KnPaymentRequestData -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is KnPaymentRequest -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is KnRequestCustomerToken -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is KnShippingConfig -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is KnSupplementaryPurchaseData -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is KnPartnerCustomer -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is KnAddress -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      is KnLineItem -> {
        stream.write(151)
        writeValue(stream, value.toList())
      }
      is KnShipping -> {
        stream.write(152)
        writeValue(stream, value.toList())
      }
      is KnShippingRecipient -> {
        stream.write(153)
        writeValue(stream, value.toList())
      }
      is KnShippingOption -> {
        stream.write(154)
        writeValue(stream, value.toList())
      }
      is KnOndemandService -> {
        stream.write(155)
        writeValue(stream, value.toList())
      }
      is KnSubscription -> {
        stream.write(156)
        writeValue(stream, value.toList())
      }
      is KnBillingPlan -> {
        stream.write(157)
        writeValue(stream, value.toList())
      }
      is KnPaymentRequestStateContext -> {
        stream.write(158)
        writeValue(stream, value.toList())
      }
      is KnCustomer -> {
        stream.write(159)
        writeValue(stream, value.toList())
      }
      is KnCustomerProfile -> {
        stream.write(160)
        writeValue(stream, value.toList())
      }
      is KnPresentationData -> {
        stream.write(161)
        writeValue(stream, value.toList())
      }
      is KnPresentationContent -> {
        stream.write(162)
        writeValue(stream, value.toList())
      }
      is KnPresentationPaymentOption -> {
        stream.write(163)
        writeValue(stream, value.toList())
      }
      is KnPresentationText -> {
        stream.write(164)
        writeValue(stream, value.toList())
      }
      is KnPresentationTextPart -> {
        stream.write(165)
        writeValue(stream, value.toList())
      }
      is KnPresentationPaymentButton -> {
        stream.write(166)
        writeValue(stream, value.toList())
      }
      is KnPresentationIcon -> {
        stream.write(167)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface KnPaymentHostApi {
  fun initiateWithId(instanceId: String, paymentRequestId: String, callback: (Result<KnPaymentRequest>) -> Unit)
  fun initiateWithData(instanceId: String, data: KnPaymentRequestData, callback: (Result<KnPaymentRequest>) -> Unit)
  fun fetch(instanceId: String, paymentRequestId: String, callback: (Result<KnPaymentRequest>) -> Unit)
  fun cancel(instanceId: String, paymentRequestId: String, callback: (Result<KnPaymentRequest>) -> Unit)
  fun presentationFetch(instanceId: String, data: KnPresentationData, callback: (Result<KnPresentationContent>) -> Unit)
  fun presentationHandleLink(instanceId: String, url: String, callback: (Result<KnPresentationContent>) -> Unit)

  companion object {
    /** The codec used by KnPaymentHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `KnPaymentHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: KnPaymentHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.klarna_network_payment.KnPaymentHostApi.initiateWithId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val instanceIdArg = args[0] as String
            val paymentRequestIdArg = args[1] as String
            api.initiateWithId(instanceIdArg, paymentRequestIdArg) { result: Result<KnPaymentRequest> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.klarna_network_payment.KnPaymentHostApi.initiateWithData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val instanceIdArg = args[0] as String
            val dataArg = args[1] as KnPaymentRequestData
            api.initiateWithData(instanceIdArg, dataArg) { result: Result<KnPaymentRequest> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.klarna_network_payment.KnPaymentHostApi.fetch$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val instanceIdArg = args[0] as String
            val paymentRequestIdArg = args[1] as String
            api.fetch(instanceIdArg, paymentRequestIdArg) { result: Result<KnPaymentRequest> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.klarna_network_payment.KnPaymentHostApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val instanceIdArg = args[0] as String
            val paymentRequestIdArg = args[1] as String
            api.cancel(instanceIdArg, paymentRequestIdArg) { result: Result<KnPaymentRequest> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.klarna_network_payment.KnPaymentHostApi.presentationFetch$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val instanceIdArg = args[0] as String
            val dataArg = args[1] as KnPresentationData
            api.presentationFetch(instanceIdArg, dataArg) { result: Result<KnPresentationContent> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.klarna_network_payment.KnPaymentHostApi.presentationHandleLink$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val instanceIdArg = args[0] as String
            val urlArg = args[1] as String
            api.presentationHandleLink(instanceIdArg, urlArg) { result: Result<KnPresentationContent> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class KnPaymentFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by KnPaymentFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onButtonPressed(viewIdArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.klarna_network_payment.KnPaymentFlutterApi.onButtonPressed$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(viewIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
