// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse(
    {Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every((MapEntry<Object?, Object?> entry) =>
            (b as Map<Object?, Object?>).containsKey(entry.key) &&
            _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}

enum KnPaymentRequestState {
  submitted,
  inProgress,
  completed,
  expired,
  canceled,
  declined,
}

enum KnPaymentRequestStateReason {
  partnerCanceled,
  paymentRequestSubmitted,
  purchaseFlowAborted,
  technicalError,
  paymentDeclined,
}

enum KnCollectCustomerProfileType {
  billingAddress,
  country,
  dateOfBirth,
  email,
  locale,
  name,
  nationalIdentification,
  phone,
}

enum KnRequestCustomerTokenScope {
  customerLogin,
  paymentCustomerNotPresent,
  paymentCustomerPresent,
}

enum KnShippingConfigMode {
  editable,
}

enum KnShippingType {
  digitalDownload,
  digitalEmail,
  digitalOther,
  physicalOther,
  pickupBox,
  pickupPoint,
  pickupStore,
  pickupWarehouse,
  toCurb,
  toDoor,
  toMailbox,
}

enum KnShippingTypeAttribute {
  contactlessDelivery,
  express,
  identificationRequired,
  leaveAtCurb,
  leaveAtDoor,
  leaveWithNeighbour,
  signatureRequired,
  tracked,
  untracked,
}

enum KnInterval {
  day,
  week,
  month,
  year,
}

enum KnFreeTrial {
  active,
  inactive,
}

enum KnPresentationIntent {
  pay,
  subscribe,
  addToWallet,
}

enum KnPresentationInstruction {
  showKlarna,
  preselectKlarna,
  showOnlyKlarna,
}

enum KnPresentationPaymentStatus {
  pendingPartnerAuthorization,
  requiresCustomerAction,
}

enum KnPresentationImageAlignment {
  left,
  right,
}

enum KnPresentationTextPartStyle {
  bold,
  italic,
  underline,
}

enum KnPresentationTextPartLinkContext {
  auth,
  info,
}

class KnPaymentRequestData {
  KnPaymentRequestData({
    required this.currency,
    required this.amount,
    this.paymentOptionId,
    this.paymentRequestReference,
    this.requestCustomerToken,
    this.shippingConfig,
    this.collectCustomerProfile,
    this.supplementaryPurchaseData,
  });

  String currency;

  int amount;

  String? paymentOptionId;

  String? paymentRequestReference;

  KnRequestCustomerToken? requestCustomerToken;

  KnShippingConfig? shippingConfig;

  List<KnCollectCustomerProfileType?>? collectCustomerProfile;

  KnSupplementaryPurchaseData? supplementaryPurchaseData;

  List<Object?> _toList() {
    return <Object?>[
      currency,
      amount,
      paymentOptionId,
      paymentRequestReference,
      requestCustomerToken,
      shippingConfig,
      collectCustomerProfile,
      supplementaryPurchaseData,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnPaymentRequestData decode(Object result) {
    result as List<Object?>;
    return KnPaymentRequestData(
      currency: result[0]! as String,
      amount: result[1]! as int,
      paymentOptionId: result[2] as String?,
      paymentRequestReference: result[3] as String?,
      requestCustomerToken: result[4] as KnRequestCustomerToken?,
      shippingConfig: result[5] as KnShippingConfig?,
      collectCustomerProfile:
          (result[6] as List<Object?>?)?.cast<KnCollectCustomerProfileType?>(),
      supplementaryPurchaseData: result[7] as KnSupplementaryPurchaseData?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnPaymentRequestData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnPaymentRequest {
  KnPaymentRequest({
    required this.paymentRequestId,
    required this.state,
    this.previousState,
    this.stateReason,
    this.paymentRequestReference,
    this.stateContext,
  });

  String paymentRequestId;

  KnPaymentRequestState state;

  KnPaymentRequestState? previousState;

  KnPaymentRequestStateReason? stateReason;

  String? paymentRequestReference;

  KnPaymentRequestStateContext? stateContext;

  List<Object?> _toList() {
    return <Object?>[
      paymentRequestId,
      state,
      previousState,
      stateReason,
      paymentRequestReference,
      stateContext,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnPaymentRequest decode(Object result) {
    result as List<Object?>;
    return KnPaymentRequest(
      paymentRequestId: result[0]! as String,
      state: result[1]! as KnPaymentRequestState,
      previousState: result[2] as KnPaymentRequestState?,
      stateReason: result[3] as KnPaymentRequestStateReason?,
      paymentRequestReference: result[4] as String?,
      stateContext: result[5] as KnPaymentRequestStateContext?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnPaymentRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnRequestCustomerToken {
  KnRequestCustomerToken({
    required this.scopes,
    this.customerTokenReference,
  });

  List<KnRequestCustomerTokenScope?> scopes;

  String? customerTokenReference;

  List<Object?> _toList() {
    return <Object?>[
      scopes,
      customerTokenReference,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnRequestCustomerToken decode(Object result) {
    result as List<Object?>;
    return KnRequestCustomerToken(
      scopes:
          (result[0] as List<Object?>?)!.cast<KnRequestCustomerTokenScope?>(),
      customerTokenReference: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnRequestCustomerToken || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnShippingConfig {
  KnShippingConfig({
    required this.mode,
    this.supportedCountries,
  });

  KnShippingConfigMode mode;

  List<String>? supportedCountries;

  List<Object?> _toList() {
    return <Object?>[
      mode,
      supportedCountries,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnShippingConfig decode(Object result) {
    result as List<Object?>;
    return KnShippingConfig(
      mode: result[0]! as KnShippingConfigMode,
      supportedCountries: (result[1] as List<Object?>?)?.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnShippingConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnSupplementaryPurchaseData {
  KnSupplementaryPurchaseData({
    this.customer,
    this.lineItems,
    this.purchaseReference,
    this.shipping,
    this.ondemandService,
    this.subscriptions,
  });

  KnPartnerCustomer? customer;

  List<KnLineItem>? lineItems;

  String? purchaseReference;

  List<KnShipping>? shipping;

  KnOndemandService? ondemandService;

  List<KnSubscription>? subscriptions;

  List<Object?> _toList() {
    return <Object?>[
      customer,
      lineItems,
      purchaseReference,
      shipping,
      ondemandService,
      subscriptions,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnSupplementaryPurchaseData decode(Object result) {
    result as List<Object?>;
    return KnSupplementaryPurchaseData(
      customer: result[0] as KnPartnerCustomer?,
      lineItems: (result[1] as List<Object?>?)?.cast<KnLineItem>(),
      purchaseReference: result[2] as String?,
      shipping: (result[3] as List<Object?>?)?.cast<KnShipping>(),
      ondemandService: result[4] as KnOndemandService?,
      subscriptions: (result[5] as List<Object?>?)?.cast<KnSubscription>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnSupplementaryPurchaseData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnPartnerCustomer {
  KnPartnerCustomer({
    this.address,
    this.email,
    this.familyName,
    this.givenName,
    this.phone,
  });

  KnAddress? address;

  String? email;

  String? familyName;

  String? givenName;

  String? phone;

  List<Object?> _toList() {
    return <Object?>[
      address,
      email,
      familyName,
      givenName,
      phone,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnPartnerCustomer decode(Object result) {
    result as List<Object?>;
    return KnPartnerCustomer(
      address: result[0] as KnAddress?,
      email: result[1] as String?,
      familyName: result[2] as String?,
      givenName: result[3] as String?,
      phone: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnPartnerCustomer || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnAddress {
  KnAddress({
    this.streetAddress,
    this.streetAddress2,
    this.city,
    this.region,
    this.postalCode,
    this.country,
  });

  String? streetAddress;

  String? streetAddress2;

  String? city;

  String? region;

  String? postalCode;

  String? country;

  List<Object?> _toList() {
    return <Object?>[
      streetAddress,
      streetAddress2,
      city,
      region,
      postalCode,
      country,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnAddress decode(Object result) {
    result as List<Object?>;
    return KnAddress(
      streetAddress: result[0] as String?,
      streetAddress2: result[1] as String?,
      city: result[2] as String?,
      region: result[3] as String?,
      postalCode: result[4] as String?,
      country: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnAddress || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnLineItem {
  KnLineItem({
    required this.name,
    required this.quantity,
    required this.totalAmount,
    this.currency,
    this.imageUrl,
    this.productIdentifier,
    this.productUrl,
    this.lineItemReference,
    this.shippingReference,
    this.subscriptionReference,
    this.totalTaxAmount,
    this.unitPrice,
  });

  String name;

  int quantity;

  int totalAmount;

  String? currency;

  String? imageUrl;

  String? productIdentifier;

  String? productUrl;

  String? lineItemReference;

  String? shippingReference;

  String? subscriptionReference;

  int? totalTaxAmount;

  int? unitPrice;

  List<Object?> _toList() {
    return <Object?>[
      name,
      quantity,
      totalAmount,
      currency,
      imageUrl,
      productIdentifier,
      productUrl,
      lineItemReference,
      shippingReference,
      subscriptionReference,
      totalTaxAmount,
      unitPrice,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnLineItem decode(Object result) {
    result as List<Object?>;
    return KnLineItem(
      name: result[0]! as String,
      quantity: result[1]! as int,
      totalAmount: result[2]! as int,
      currency: result[3] as String?,
      imageUrl: result[4] as String?,
      productIdentifier: result[5] as String?,
      productUrl: result[6] as String?,
      lineItemReference: result[7] as String?,
      shippingReference: result[8] as String?,
      subscriptionReference: result[9] as String?,
      totalTaxAmount: result[10] as int?,
      unitPrice: result[11] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnLineItem || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnShipping {
  KnShipping({
    this.address,
    this.recipient,
    this.shippingOption,
    this.shippingReference,
  });

  KnAddress? address;

  KnShippingRecipient? recipient;

  KnShippingOption? shippingOption;

  String? shippingReference;

  List<Object?> _toList() {
    return <Object?>[
      address,
      recipient,
      shippingOption,
      shippingReference,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnShipping decode(Object result) {
    result as List<Object?>;
    return KnShipping(
      address: result[0] as KnAddress?,
      recipient: result[1] as KnShippingRecipient?,
      shippingOption: result[2] as KnShippingOption?,
      shippingReference: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnShipping || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnShippingRecipient {
  KnShippingRecipient({
    required this.familyName,
    required this.givenName,
    this.attention,
    this.email,
    this.phone,
  });

  String familyName;

  String givenName;

  String? attention;

  String? email;

  String? phone;

  List<Object?> _toList() {
    return <Object?>[
      familyName,
      givenName,
      attention,
      email,
      phone,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnShippingRecipient decode(Object result) {
    result as List<Object?>;
    return KnShippingRecipient(
      familyName: result[0]! as String,
      givenName: result[1]! as String,
      attention: result[2] as String?,
      email: result[3] as String?,
      phone: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnShippingRecipient || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnShippingOption {
  KnShippingOption({
    required this.shippingType,
    this.shippingCarrier,
    this.shippingTypeAttributes,
  });

  KnShippingType shippingType;

  String? shippingCarrier;

  List<KnShippingTypeAttribute?>? shippingTypeAttributes;

  List<Object?> _toList() {
    return <Object?>[
      shippingType,
      shippingCarrier,
      shippingTypeAttributes,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnShippingOption decode(Object result) {
    result as List<Object?>;
    return KnShippingOption(
      shippingType: result[0]! as KnShippingType,
      shippingCarrier: result[1] as String?,
      shippingTypeAttributes:
          (result[2] as List<Object?>?)?.cast<KnShippingTypeAttribute?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnShippingOption || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnOndemandService {
  KnOndemandService({
    this.currency,
    this.averageAmount,
    this.minimumAmount,
    this.maximumAmount,
    this.purchaseInterval,
    this.purchaseIntervalFrequency,
  });

  String? currency;

  int? averageAmount;

  int? minimumAmount;

  int? maximumAmount;

  KnInterval? purchaseInterval;

  int? purchaseIntervalFrequency;

  List<Object?> _toList() {
    return <Object?>[
      currency,
      averageAmount,
      minimumAmount,
      maximumAmount,
      purchaseInterval,
      purchaseIntervalFrequency,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnOndemandService decode(Object result) {
    result as List<Object?>;
    return KnOndemandService(
      currency: result[0] as String?,
      averageAmount: result[1] as int?,
      minimumAmount: result[2] as int?,
      maximumAmount: result[3] as int?,
      purchaseInterval: result[4] as KnInterval?,
      purchaseIntervalFrequency: result[5] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnOndemandService || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnSubscription {
  KnSubscription({
    required this.subscriptionReference,
    this.name,
    this.freeTrial,
    this.billingPlans,
  });

  String subscriptionReference;

  String? name;

  KnFreeTrial? freeTrial;

  List<KnBillingPlan>? billingPlans;

  List<Object?> _toList() {
    return <Object?>[
      subscriptionReference,
      name,
      freeTrial,
      billingPlans,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnSubscription decode(Object result) {
    result as List<Object?>;
    return KnSubscription(
      subscriptionReference: result[0]! as String,
      name: result[1] as String?,
      freeTrial: result[2] as KnFreeTrial?,
      billingPlans: (result[3] as List<Object?>?)?.cast<KnBillingPlan>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnSubscription || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnBillingPlan {
  KnBillingPlan({
    required this.billingAmount,
    required this.from,
    required this.interval,
    required this.intervalFrequency,
    this.currency,
  });

  int billingAmount;

  String from;

  KnInterval interval;

  int intervalFrequency;

  String? currency;

  List<Object?> _toList() {
    return <Object?>[
      billingAmount,
      from,
      interval,
      intervalFrequency,
      currency,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnBillingPlan decode(Object result) {
    result as List<Object?>;
    return KnBillingPlan(
      billingAmount: result[0]! as int,
      from: result[1]! as String,
      interval: result[2]! as KnInterval,
      intervalFrequency: result[3]! as int,
      currency: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnBillingPlan || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnPaymentRequestStateContext {
  KnPaymentRequestStateContext({
    this.klarnaNetworkSessionToken,
    this.klarnaCustomer,
    this.shipping,
  });

  String? klarnaNetworkSessionToken;

  KnCustomer? klarnaCustomer;

  KnShipping? shipping;

  List<Object?> _toList() {
    return <Object?>[
      klarnaNetworkSessionToken,
      klarnaCustomer,
      shipping,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnPaymentRequestStateContext decode(Object result) {
    result as List<Object?>;
    return KnPaymentRequestStateContext(
      klarnaNetworkSessionToken: result[0] as String?,
      klarnaCustomer: result[1] as KnCustomer?,
      shipping: result[2] as KnShipping?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnPaymentRequestStateContext ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnCustomer {
  KnCustomer({
    this.customerToken,
    this.customerTokenReference,
    this.customerProfile,
  });

  String? customerToken;

  String? customerTokenReference;

  KnCustomerProfile? customerProfile;

  List<Object?> _toList() {
    return <Object?>[
      customerToken,
      customerTokenReference,
      customerProfile,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnCustomer decode(Object result) {
    result as List<Object?>;
    return KnCustomer(
      customerToken: result[0] as String?,
      customerTokenReference: result[1] as String?,
      customerProfile: result[2] as KnCustomerProfile?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnCustomer || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnCustomerProfile {
  KnCustomerProfile({
    this.address,
    this.customerId,
    this.country,
    this.email,
    this.emailVerified,
    this.familyName,
    this.givenName,
    this.locale,
    this.phone,
    this.phoneVerified,
  });

  KnAddress? address;

  String? customerId;

  String? country;

  String? email;

  bool? emailVerified;

  String? familyName;

  String? givenName;

  String? locale;

  String? phone;

  bool? phoneVerified;

  List<Object?> _toList() {
    return <Object?>[
      address,
      customerId,
      country,
      email,
      emailVerified,
      familyName,
      givenName,
      locale,
      phone,
      phoneVerified,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnCustomerProfile decode(Object result) {
    result as List<Object?>;
    return KnCustomerProfile(
      address: result[0] as KnAddress?,
      customerId: result[1] as String?,
      country: result[2] as String?,
      email: result[3] as String?,
      emailVerified: result[4] as bool?,
      familyName: result[5] as String?,
      givenName: result[6] as String?,
      locale: result[7] as String?,
      phone: result[8] as String?,
      phoneVerified: result[9] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnCustomerProfile || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnPresentationData {
  KnPresentationData({
    required this.currency,
    required this.amount,
    this.intent,
    this.paymentProgramEnablementCodes,
    this.subscriptionBillingInterval,
    this.subscriptionBillingIntervalFrequency,
  });

  String currency;

  int amount;

  KnPresentationIntent? intent;

  List<String>? paymentProgramEnablementCodes;

  KnInterval? subscriptionBillingInterval;

  int? subscriptionBillingIntervalFrequency;

  List<Object?> _toList() {
    return <Object?>[
      currency,
      amount,
      intent,
      paymentProgramEnablementCodes,
      subscriptionBillingInterval,
      subscriptionBillingIntervalFrequency,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnPresentationData decode(Object result) {
    result as List<Object?>;
    return KnPresentationData(
      currency: result[0]! as String,
      amount: result[1]! as int,
      intent: result[2] as KnPresentationIntent?,
      paymentProgramEnablementCodes:
          (result[3] as List<Object?>?)?.cast<String>(),
      subscriptionBillingInterval: result[4] as KnInterval?,
      subscriptionBillingIntervalFrequency: result[5] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnPresentationData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnPresentationContent {
  KnPresentationContent({
    required this.instruction,
    this.paymentStatus,
    this.paymentOption,
    this.savedPaymentOption,
  });

  KnPresentationInstruction instruction;

  KnPresentationPaymentStatus? paymentStatus;

  KnPresentationPaymentOption? paymentOption;

  KnPresentationPaymentOption? savedPaymentOption;

  List<Object?> _toList() {
    return <Object?>[
      instruction,
      paymentStatus,
      paymentOption,
      savedPaymentOption,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnPresentationContent decode(Object result) {
    result as List<Object?>;
    return KnPresentationContent(
      instruction: result[0]! as KnPresentationInstruction,
      paymentStatus: result[1] as KnPresentationPaymentStatus?,
      paymentOption: result[2] as KnPresentationPaymentOption?,
      savedPaymentOption: result[3] as KnPresentationPaymentOption?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnPresentationContent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnPresentationPaymentOption {
  KnPresentationPaymentOption({
    required this.paymentOptionId,
    this.header,
    this.badge,
    this.subheader,
    this.message,
    this.terms,
    this.paymentButton,
    this.icon,
  });

  String paymentOptionId;

  KnPresentationText? header;

  KnPresentationText? badge;

  KnPresentationText? subheader;

  KnPresentationText? message;

  KnPresentationText? terms;

  KnPresentationPaymentButton? paymentButton;

  KnPresentationIcon? icon;

  List<Object?> _toList() {
    return <Object?>[
      paymentOptionId,
      header,
      badge,
      subheader,
      message,
      terms,
      paymentButton,
      icon,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnPresentationPaymentOption decode(Object result) {
    result as List<Object?>;
    return KnPresentationPaymentOption(
      paymentOptionId: result[0]! as String,
      header: result[1] as KnPresentationText?,
      badge: result[2] as KnPresentationText?,
      subheader: result[3] as KnPresentationText?,
      message: result[4] as KnPresentationText?,
      terms: result[5] as KnPresentationText?,
      paymentButton: result[6] as KnPresentationPaymentButton?,
      icon: result[7] as KnPresentationIcon?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnPresentationPaymentOption ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnPresentationText {
  KnPresentationText({
    required this.type,
    this.text,
    this.parts,
  });

  String type;

  String? text;

  List<KnPresentationTextPart>? parts;

  List<Object?> _toList() {
    return <Object?>[
      type,
      text,
      parts,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnPresentationText decode(Object result) {
    result as List<Object?>;
    return KnPresentationText(
      type: result[0]! as String,
      text: result[1] as String?,
      parts: (result[2] as List<Object?>?)?.cast<KnPresentationTextPart>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnPresentationText || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnPresentationTextPart {
  KnPresentationTextPart({
    required this.type,
    required this.text,
    this.url,
    this.context,
    this.styles,
  });

  String type;

  String text;

  String? url;

  KnPresentationTextPartLinkContext? context;

  List<KnPresentationTextPartStyle?>? styles;

  List<Object?> _toList() {
    return <Object?>[
      type,
      text,
      url,
      context,
      styles,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnPresentationTextPart decode(Object result) {
    result as List<Object?>;
    return KnPresentationTextPart(
      type: result[0]! as String,
      text: result[1]! as String,
      url: result[2] as String?,
      context: result[3] as KnPresentationTextPartLinkContext?,
      styles:
          (result[4] as List<Object?>?)?.cast<KnPresentationTextPartStyle?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnPresentationTextPart || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnPresentationPaymentButton {
  KnPresentationPaymentButton({
    required this.text,
    this.imageUrl,
    this.imageAlignment,
  });

  String text;

  String? imageUrl;

  KnPresentationImageAlignment? imageAlignment;

  List<Object?> _toList() {
    return <Object?>[
      text,
      imageUrl,
      imageAlignment,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnPresentationPaymentButton decode(Object result) {
    result as List<Object?>;
    return KnPresentationPaymentButton(
      text: result[0]! as String,
      imageUrl: result[1] as String?,
      imageAlignment: result[2] as KnPresentationImageAlignment?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnPresentationPaymentButton ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KnPresentationIcon {
  KnPresentationIcon({
    this.alt,
    this.badgeImageUrl,
    this.rectangleImageUrl,
    this.squareImageUrl,
  });

  String? alt;

  String? badgeImageUrl;

  String? rectangleImageUrl;

  String? squareImageUrl;

  List<Object?> _toList() {
    return <Object?>[
      alt,
      badgeImageUrl,
      rectangleImageUrl,
      squareImageUrl,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KnPresentationIcon decode(Object result) {
    result as List<Object?>;
    return KnPresentationIcon(
      alt: result[0] as String?,
      badgeImageUrl: result[1] as String?,
      rectangleImageUrl: result[2] as String?,
      squareImageUrl: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KnPresentationIcon || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is KnPaymentRequestState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is KnPaymentRequestStateReason) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is KnCollectCustomerProfileType) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is KnRequestCustomerTokenScope) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is KnShippingConfigMode) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is KnShippingType) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is KnShippingTypeAttribute) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    } else if (value is KnInterval) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    } else if (value is KnFreeTrial) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    } else if (value is KnPresentationIntent) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    } else if (value is KnPresentationInstruction) {
      buffer.putUint8(139);
      writeValue(buffer, value.index);
    } else if (value is KnPresentationPaymentStatus) {
      buffer.putUint8(140);
      writeValue(buffer, value.index);
    } else if (value is KnPresentationImageAlignment) {
      buffer.putUint8(141);
      writeValue(buffer, value.index);
    } else if (value is KnPresentationTextPartStyle) {
      buffer.putUint8(142);
      writeValue(buffer, value.index);
    } else if (value is KnPresentationTextPartLinkContext) {
      buffer.putUint8(143);
      writeValue(buffer, value.index);
    } else if (value is KnPaymentRequestData) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is KnPaymentRequest) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is KnRequestCustomerToken) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is KnShippingConfig) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is KnSupplementaryPurchaseData) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is KnPartnerCustomer) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else if (value is KnAddress) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    } else if (value is KnLineItem) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else if (value is KnShipping) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    } else if (value is KnShippingRecipient) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    } else if (value is KnShippingOption) {
      buffer.putUint8(154);
      writeValue(buffer, value.encode());
    } else if (value is KnOndemandService) {
      buffer.putUint8(155);
      writeValue(buffer, value.encode());
    } else if (value is KnSubscription) {
      buffer.putUint8(156);
      writeValue(buffer, value.encode());
    } else if (value is KnBillingPlan) {
      buffer.putUint8(157);
      writeValue(buffer, value.encode());
    } else if (value is KnPaymentRequestStateContext) {
      buffer.putUint8(158);
      writeValue(buffer, value.encode());
    } else if (value is KnCustomer) {
      buffer.putUint8(159);
      writeValue(buffer, value.encode());
    } else if (value is KnCustomerProfile) {
      buffer.putUint8(160);
      writeValue(buffer, value.encode());
    } else if (value is KnPresentationData) {
      buffer.putUint8(161);
      writeValue(buffer, value.encode());
    } else if (value is KnPresentationContent) {
      buffer.putUint8(162);
      writeValue(buffer, value.encode());
    } else if (value is KnPresentationPaymentOption) {
      buffer.putUint8(163);
      writeValue(buffer, value.encode());
    } else if (value is KnPresentationText) {
      buffer.putUint8(164);
      writeValue(buffer, value.encode());
    } else if (value is KnPresentationTextPart) {
      buffer.putUint8(165);
      writeValue(buffer, value.encode());
    } else if (value is KnPresentationPaymentButton) {
      buffer.putUint8(166);
      writeValue(buffer, value.encode());
    } else if (value is KnPresentationIcon) {
      buffer.putUint8(167);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : KnPaymentRequestState.values[value];
      case 130:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : KnPaymentRequestStateReason.values[value];
      case 131:
        final int? value = readValue(buffer) as int?;
        return value == null
            ? null
            : KnCollectCustomerProfileType.values[value];
      case 132:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : KnRequestCustomerTokenScope.values[value];
      case 133:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : KnShippingConfigMode.values[value];
      case 134:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : KnShippingType.values[value];
      case 135:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : KnShippingTypeAttribute.values[value];
      case 136:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : KnInterval.values[value];
      case 137:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : KnFreeTrial.values[value];
      case 138:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : KnPresentationIntent.values[value];
      case 139:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : KnPresentationInstruction.values[value];
      case 140:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : KnPresentationPaymentStatus.values[value];
      case 141:
        final int? value = readValue(buffer) as int?;
        return value == null
            ? null
            : KnPresentationImageAlignment.values[value];
      case 142:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : KnPresentationTextPartStyle.values[value];
      case 143:
        final int? value = readValue(buffer) as int?;
        return value == null
            ? null
            : KnPresentationTextPartLinkContext.values[value];
      case 144:
        return KnPaymentRequestData.decode(readValue(buffer)!);
      case 145:
        return KnPaymentRequest.decode(readValue(buffer)!);
      case 146:
        return KnRequestCustomerToken.decode(readValue(buffer)!);
      case 147:
        return KnShippingConfig.decode(readValue(buffer)!);
      case 148:
        return KnSupplementaryPurchaseData.decode(readValue(buffer)!);
      case 149:
        return KnPartnerCustomer.decode(readValue(buffer)!);
      case 150:
        return KnAddress.decode(readValue(buffer)!);
      case 151:
        return KnLineItem.decode(readValue(buffer)!);
      case 152:
        return KnShipping.decode(readValue(buffer)!);
      case 153:
        return KnShippingRecipient.decode(readValue(buffer)!);
      case 154:
        return KnShippingOption.decode(readValue(buffer)!);
      case 155:
        return KnOndemandService.decode(readValue(buffer)!);
      case 156:
        return KnSubscription.decode(readValue(buffer)!);
      case 157:
        return KnBillingPlan.decode(readValue(buffer)!);
      case 158:
        return KnPaymentRequestStateContext.decode(readValue(buffer)!);
      case 159:
        return KnCustomer.decode(readValue(buffer)!);
      case 160:
        return KnCustomerProfile.decode(readValue(buffer)!);
      case 161:
        return KnPresentationData.decode(readValue(buffer)!);
      case 162:
        return KnPresentationContent.decode(readValue(buffer)!);
      case 163:
        return KnPresentationPaymentOption.decode(readValue(buffer)!);
      case 164:
        return KnPresentationText.decode(readValue(buffer)!);
      case 165:
        return KnPresentationTextPart.decode(readValue(buffer)!);
      case 166:
        return KnPresentationPaymentButton.decode(readValue(buffer)!);
      case 167:
        return KnPresentationIcon.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class KnPaymentHostApi {
  /// Constructor for [KnPaymentHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  KnPaymentHostApi(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<KnPaymentRequest> initiateWithId(
      String instanceId, String paymentRequestId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.klarna_network_payment.KnPaymentHostApi.initiateWithId$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[instanceId, paymentRequestId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as KnPaymentRequest?)!;
    }
  }

  Future<KnPaymentRequest> initiateWithData(
      String instanceId, KnPaymentRequestData data) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.klarna_network_payment.KnPaymentHostApi.initiateWithData$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[instanceId, data]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as KnPaymentRequest?)!;
    }
  }

  Future<KnPaymentRequest> fetch(
      String instanceId, String paymentRequestId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.klarna_network_payment.KnPaymentHostApi.fetch$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[instanceId, paymentRequestId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as KnPaymentRequest?)!;
    }
  }

  Future<KnPaymentRequest> cancel(
      String instanceId, String paymentRequestId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.klarna_network_payment.KnPaymentHostApi.cancel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[instanceId, paymentRequestId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as KnPaymentRequest?)!;
    }
  }

  Future<KnPresentationContent> presentationFetch(
      String instanceId, KnPresentationData data) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.klarna_network_payment.KnPaymentHostApi.presentationFetch$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[instanceId, data]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as KnPresentationContent?)!;
    }
  }

  Future<KnPresentationContent> presentationHandleLink(
      String instanceId, String url) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.klarna_network_payment.KnPaymentHostApi.presentationHandleLink$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[instanceId, url]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as KnPresentationContent?)!;
    }
  }
}

abstract class KnPaymentFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onButtonPressed(int viewId);

  static void setUp(
    KnPaymentFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix =
        messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<
          Object?> pigeonVar_channel = BasicMessageChannel<
              Object?>(
          'dev.flutter.pigeon.klarna_network_payment.KnPaymentFlutterApi.onButtonPressed$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.klarna_network_payment.KnPaymentFlutterApi.onButtonPressed was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_viewId = (args[0] as int?);
          assert(arg_viewId != null,
              'Argument for dev.flutter.pigeon.klarna_network_payment.KnPaymentFlutterApi.onButtonPressed was null, expected non-null int.');
          try {
            api.onButtonPressed(arg_viewId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
