// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum KnPaymentRequestState: Int {
  case submitted = 0
  case inProgress = 1
  case completed = 2
  case expired = 3
  case canceled = 4
  case declined = 5
}

enum KnPaymentRequestStateReason: Int {
  case partnerCanceled = 0
  case paymentRequestSubmitted = 1
  case purchaseFlowAborted = 2
  case technicalError = 3
  case paymentDeclined = 4
}

enum KnCollectCustomerProfileType: Int {
  case billingAddress = 0
  case country = 1
  case dateOfBirth = 2
  case email = 3
  case locale = 4
  case name = 5
  case nationalIdentification = 6
  case phone = 7
}

enum KnRequestCustomerTokenScope: Int {
  case customerLogin = 0
  case paymentCustomerNotPresent = 1
  case paymentCustomerPresent = 2
}

enum KnShippingConfigMode: Int {
  case editable = 0
}

enum KnShippingType: Int {
  case digitalDownload = 0
  case digitalEmail = 1
  case digitalOther = 2
  case physicalOther = 3
  case pickupBox = 4
  case pickupPoint = 5
  case pickupStore = 6
  case pickupWarehouse = 7
  case toCurb = 8
  case toDoor = 9
  case toMailbox = 10
}

enum KnShippingTypeAttribute: Int {
  case contactlessDelivery = 0
  case express = 1
  case identificationRequired = 2
  case leaveAtCurb = 3
  case leaveAtDoor = 4
  case leaveWithNeighbour = 5
  case signatureRequired = 6
  case tracked = 7
  case untracked = 8
}

enum KnInterval: Int {
  case day = 0
  case week = 1
  case month = 2
  case year = 3
}

enum KnFreeTrial: Int {
  case active = 0
  case inactive = 1
}

enum KnPresentationIntent: Int {
  case pay = 0
  case subscribe = 1
  case addToWallet = 2
}

enum KnPresentationInstruction: Int {
  case showKlarna = 0
  case preselectKlarna = 1
  case showOnlyKlarna = 2
}

enum KnPresentationPaymentStatus: Int {
  case pendingPartnerAuthorization = 0
  case requiresCustomerAction = 1
}

enum KnPresentationImageAlignment: Int {
  case left = 0
  case right = 1
}

enum KnPresentationTextPartStyle: Int {
  case bold = 0
  case italic = 1
  case underline = 2
}

enum KnPresentationTextPartLinkContext: Int {
  case auth = 0
  case info = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnPaymentRequestData: Hashable {
  var currency: String
  var amount: Int64
  var paymentOptionId: String? = nil
  var paymentRequestReference: String? = nil
  var requestCustomerToken: KnRequestCustomerToken? = nil
  var shippingConfig: KnShippingConfig? = nil
  var collectCustomerProfile: [KnCollectCustomerProfileType?]? = nil
  var supplementaryPurchaseData: KnSupplementaryPurchaseData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnPaymentRequestData? {
    let currency = pigeonVar_list[0] as! String
    let amount = pigeonVar_list[1] as! Int64
    let paymentOptionId: String? = nilOrValue(pigeonVar_list[2])
    let paymentRequestReference: String? = nilOrValue(pigeonVar_list[3])
    let requestCustomerToken: KnRequestCustomerToken? = nilOrValue(pigeonVar_list[4])
    let shippingConfig: KnShippingConfig? = nilOrValue(pigeonVar_list[5])
    let collectCustomerProfile: [KnCollectCustomerProfileType?]? = nilOrValue(pigeonVar_list[6])
    let supplementaryPurchaseData: KnSupplementaryPurchaseData? = nilOrValue(pigeonVar_list[7])

    return KnPaymentRequestData(
      currency: currency,
      amount: amount,
      paymentOptionId: paymentOptionId,
      paymentRequestReference: paymentRequestReference,
      requestCustomerToken: requestCustomerToken,
      shippingConfig: shippingConfig,
      collectCustomerProfile: collectCustomerProfile,
      supplementaryPurchaseData: supplementaryPurchaseData
    )
  }
  func toList() -> [Any?] {
    return [
      currency,
      amount,
      paymentOptionId,
      paymentRequestReference,
      requestCustomerToken,
      shippingConfig,
      collectCustomerProfile,
      supplementaryPurchaseData,
    ]
  }
  static func == (lhs: KnPaymentRequestData, rhs: KnPaymentRequestData) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnPaymentRequest: Hashable {
  var paymentRequestId: String
  var state: KnPaymentRequestState
  var previousState: KnPaymentRequestState? = nil
  var stateReason: KnPaymentRequestStateReason? = nil
  var paymentRequestReference: String? = nil
  var stateContext: KnPaymentRequestStateContext? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnPaymentRequest? {
    let paymentRequestId = pigeonVar_list[0] as! String
    let state = pigeonVar_list[1] as! KnPaymentRequestState
    let previousState: KnPaymentRequestState? = nilOrValue(pigeonVar_list[2])
    let stateReason: KnPaymentRequestStateReason? = nilOrValue(pigeonVar_list[3])
    let paymentRequestReference: String? = nilOrValue(pigeonVar_list[4])
    let stateContext: KnPaymentRequestStateContext? = nilOrValue(pigeonVar_list[5])

    return KnPaymentRequest(
      paymentRequestId: paymentRequestId,
      state: state,
      previousState: previousState,
      stateReason: stateReason,
      paymentRequestReference: paymentRequestReference,
      stateContext: stateContext
    )
  }
  func toList() -> [Any?] {
    return [
      paymentRequestId,
      state,
      previousState,
      stateReason,
      paymentRequestReference,
      stateContext,
    ]
  }
  static func == (lhs: KnPaymentRequest, rhs: KnPaymentRequest) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnRequestCustomerToken: Hashable {
  var scopes: [KnRequestCustomerTokenScope?]
  var customerTokenReference: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnRequestCustomerToken? {
    let scopes = pigeonVar_list[0] as! [KnRequestCustomerTokenScope?]
    let customerTokenReference: String? = nilOrValue(pigeonVar_list[1])

    return KnRequestCustomerToken(
      scopes: scopes,
      customerTokenReference: customerTokenReference
    )
  }
  func toList() -> [Any?] {
    return [
      scopes,
      customerTokenReference,
    ]
  }
  static func == (lhs: KnRequestCustomerToken, rhs: KnRequestCustomerToken) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnShippingConfig: Hashable {
  var mode: KnShippingConfigMode
  var supportedCountries: [String]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnShippingConfig? {
    let mode = pigeonVar_list[0] as! KnShippingConfigMode
    let supportedCountries: [String]? = nilOrValue(pigeonVar_list[1])

    return KnShippingConfig(
      mode: mode,
      supportedCountries: supportedCountries
    )
  }
  func toList() -> [Any?] {
    return [
      mode,
      supportedCountries,
    ]
  }
  static func == (lhs: KnShippingConfig, rhs: KnShippingConfig) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnSupplementaryPurchaseData: Hashable {
  var customer: KnPartnerCustomer? = nil
  var lineItems: [KnLineItem]? = nil
  var purchaseReference: String? = nil
  var shipping: [KnShipping]? = nil
  var ondemandService: KnOndemandService? = nil
  var subscriptions: [KnSubscription]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnSupplementaryPurchaseData? {
    let customer: KnPartnerCustomer? = nilOrValue(pigeonVar_list[0])
    let lineItems: [KnLineItem]? = nilOrValue(pigeonVar_list[1])
    let purchaseReference: String? = nilOrValue(pigeonVar_list[2])
    let shipping: [KnShipping]? = nilOrValue(pigeonVar_list[3])
    let ondemandService: KnOndemandService? = nilOrValue(pigeonVar_list[4])
    let subscriptions: [KnSubscription]? = nilOrValue(pigeonVar_list[5])

    return KnSupplementaryPurchaseData(
      customer: customer,
      lineItems: lineItems,
      purchaseReference: purchaseReference,
      shipping: shipping,
      ondemandService: ondemandService,
      subscriptions: subscriptions
    )
  }
  func toList() -> [Any?] {
    return [
      customer,
      lineItems,
      purchaseReference,
      shipping,
      ondemandService,
      subscriptions,
    ]
  }
  static func == (lhs: KnSupplementaryPurchaseData, rhs: KnSupplementaryPurchaseData) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnPartnerCustomer: Hashable {
  var address: KnAddress? = nil
  var email: String? = nil
  var familyName: String? = nil
  var givenName: String? = nil
  var phone: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnPartnerCustomer? {
    let address: KnAddress? = nilOrValue(pigeonVar_list[0])
    let email: String? = nilOrValue(pigeonVar_list[1])
    let familyName: String? = nilOrValue(pigeonVar_list[2])
    let givenName: String? = nilOrValue(pigeonVar_list[3])
    let phone: String? = nilOrValue(pigeonVar_list[4])

    return KnPartnerCustomer(
      address: address,
      email: email,
      familyName: familyName,
      givenName: givenName,
      phone: phone
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      email,
      familyName,
      givenName,
      phone,
    ]
  }
  static func == (lhs: KnPartnerCustomer, rhs: KnPartnerCustomer) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnAddress: Hashable {
  var streetAddress: String? = nil
  var streetAddress2: String? = nil
  var city: String? = nil
  var region: String? = nil
  var postalCode: String? = nil
  var country: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnAddress? {
    let streetAddress: String? = nilOrValue(pigeonVar_list[0])
    let streetAddress2: String? = nilOrValue(pigeonVar_list[1])
    let city: String? = nilOrValue(pigeonVar_list[2])
    let region: String? = nilOrValue(pigeonVar_list[3])
    let postalCode: String? = nilOrValue(pigeonVar_list[4])
    let country: String? = nilOrValue(pigeonVar_list[5])

    return KnAddress(
      streetAddress: streetAddress,
      streetAddress2: streetAddress2,
      city: city,
      region: region,
      postalCode: postalCode,
      country: country
    )
  }
  func toList() -> [Any?] {
    return [
      streetAddress,
      streetAddress2,
      city,
      region,
      postalCode,
      country,
    ]
  }
  static func == (lhs: KnAddress, rhs: KnAddress) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnLineItem: Hashable {
  var name: String
  var quantity: Int64
  var totalAmount: Int64
  var currency: String? = nil
  var imageUrl: String? = nil
  var productIdentifier: String? = nil
  var productUrl: String? = nil
  var lineItemReference: String? = nil
  var shippingReference: String? = nil
  var subscriptionReference: String? = nil
  var totalTaxAmount: Int64? = nil
  var unitPrice: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnLineItem? {
    let name = pigeonVar_list[0] as! String
    let quantity = pigeonVar_list[1] as! Int64
    let totalAmount = pigeonVar_list[2] as! Int64
    let currency: String? = nilOrValue(pigeonVar_list[3])
    let imageUrl: String? = nilOrValue(pigeonVar_list[4])
    let productIdentifier: String? = nilOrValue(pigeonVar_list[5])
    let productUrl: String? = nilOrValue(pigeonVar_list[6])
    let lineItemReference: String? = nilOrValue(pigeonVar_list[7])
    let shippingReference: String? = nilOrValue(pigeonVar_list[8])
    let subscriptionReference: String? = nilOrValue(pigeonVar_list[9])
    let totalTaxAmount: Int64? = nilOrValue(pigeonVar_list[10])
    let unitPrice: Int64? = nilOrValue(pigeonVar_list[11])

    return KnLineItem(
      name: name,
      quantity: quantity,
      totalAmount: totalAmount,
      currency: currency,
      imageUrl: imageUrl,
      productIdentifier: productIdentifier,
      productUrl: productUrl,
      lineItemReference: lineItemReference,
      shippingReference: shippingReference,
      subscriptionReference: subscriptionReference,
      totalTaxAmount: totalTaxAmount,
      unitPrice: unitPrice
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      quantity,
      totalAmount,
      currency,
      imageUrl,
      productIdentifier,
      productUrl,
      lineItemReference,
      shippingReference,
      subscriptionReference,
      totalTaxAmount,
      unitPrice,
    ]
  }
  static func == (lhs: KnLineItem, rhs: KnLineItem) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnShipping: Hashable {
  var address: KnAddress? = nil
  var recipient: KnShippingRecipient? = nil
  var shippingOption: KnShippingOption? = nil
  var shippingReference: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnShipping? {
    let address: KnAddress? = nilOrValue(pigeonVar_list[0])
    let recipient: KnShippingRecipient? = nilOrValue(pigeonVar_list[1])
    let shippingOption: KnShippingOption? = nilOrValue(pigeonVar_list[2])
    let shippingReference: String? = nilOrValue(pigeonVar_list[3])

    return KnShipping(
      address: address,
      recipient: recipient,
      shippingOption: shippingOption,
      shippingReference: shippingReference
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      recipient,
      shippingOption,
      shippingReference,
    ]
  }
  static func == (lhs: KnShipping, rhs: KnShipping) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnShippingRecipient: Hashable {
  var familyName: String
  var givenName: String
  var attention: String? = nil
  var email: String? = nil
  var phone: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnShippingRecipient? {
    let familyName = pigeonVar_list[0] as! String
    let givenName = pigeonVar_list[1] as! String
    let attention: String? = nilOrValue(pigeonVar_list[2])
    let email: String? = nilOrValue(pigeonVar_list[3])
    let phone: String? = nilOrValue(pigeonVar_list[4])

    return KnShippingRecipient(
      familyName: familyName,
      givenName: givenName,
      attention: attention,
      email: email,
      phone: phone
    )
  }
  func toList() -> [Any?] {
    return [
      familyName,
      givenName,
      attention,
      email,
      phone,
    ]
  }
  static func == (lhs: KnShippingRecipient, rhs: KnShippingRecipient) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnShippingOption: Hashable {
  var shippingType: KnShippingType
  var shippingCarrier: String? = nil
  var shippingTypeAttributes: [KnShippingTypeAttribute?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnShippingOption? {
    let shippingType = pigeonVar_list[0] as! KnShippingType
    let shippingCarrier: String? = nilOrValue(pigeonVar_list[1])
    let shippingTypeAttributes: [KnShippingTypeAttribute?]? = nilOrValue(pigeonVar_list[2])

    return KnShippingOption(
      shippingType: shippingType,
      shippingCarrier: shippingCarrier,
      shippingTypeAttributes: shippingTypeAttributes
    )
  }
  func toList() -> [Any?] {
    return [
      shippingType,
      shippingCarrier,
      shippingTypeAttributes,
    ]
  }
  static func == (lhs: KnShippingOption, rhs: KnShippingOption) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnOndemandService: Hashable {
  var currency: String? = nil
  var averageAmount: Int64? = nil
  var minimumAmount: Int64? = nil
  var maximumAmount: Int64? = nil
  var purchaseInterval: KnInterval? = nil
  var purchaseIntervalFrequency: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnOndemandService? {
    let currency: String? = nilOrValue(pigeonVar_list[0])
    let averageAmount: Int64? = nilOrValue(pigeonVar_list[1])
    let minimumAmount: Int64? = nilOrValue(pigeonVar_list[2])
    let maximumAmount: Int64? = nilOrValue(pigeonVar_list[3])
    let purchaseInterval: KnInterval? = nilOrValue(pigeonVar_list[4])
    let purchaseIntervalFrequency: Int64? = nilOrValue(pigeonVar_list[5])

    return KnOndemandService(
      currency: currency,
      averageAmount: averageAmount,
      minimumAmount: minimumAmount,
      maximumAmount: maximumAmount,
      purchaseInterval: purchaseInterval,
      purchaseIntervalFrequency: purchaseIntervalFrequency
    )
  }
  func toList() -> [Any?] {
    return [
      currency,
      averageAmount,
      minimumAmount,
      maximumAmount,
      purchaseInterval,
      purchaseIntervalFrequency,
    ]
  }
  static func == (lhs: KnOndemandService, rhs: KnOndemandService) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnSubscription: Hashable {
  var subscriptionReference: String
  var name: String? = nil
  var freeTrial: KnFreeTrial? = nil
  var billingPlans: [KnBillingPlan]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnSubscription? {
    let subscriptionReference = pigeonVar_list[0] as! String
    let name: String? = nilOrValue(pigeonVar_list[1])
    let freeTrial: KnFreeTrial? = nilOrValue(pigeonVar_list[2])
    let billingPlans: [KnBillingPlan]? = nilOrValue(pigeonVar_list[3])

    return KnSubscription(
      subscriptionReference: subscriptionReference,
      name: name,
      freeTrial: freeTrial,
      billingPlans: billingPlans
    )
  }
  func toList() -> [Any?] {
    return [
      subscriptionReference,
      name,
      freeTrial,
      billingPlans,
    ]
  }
  static func == (lhs: KnSubscription, rhs: KnSubscription) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnBillingPlan: Hashable {
  var billingAmount: Int64
  var from: String
  var interval: KnInterval
  var intervalFrequency: Int64
  var currency: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnBillingPlan? {
    let billingAmount = pigeonVar_list[0] as! Int64
    let from = pigeonVar_list[1] as! String
    let interval = pigeonVar_list[2] as! KnInterval
    let intervalFrequency = pigeonVar_list[3] as! Int64
    let currency: String? = nilOrValue(pigeonVar_list[4])

    return KnBillingPlan(
      billingAmount: billingAmount,
      from: from,
      interval: interval,
      intervalFrequency: intervalFrequency,
      currency: currency
    )
  }
  func toList() -> [Any?] {
    return [
      billingAmount,
      from,
      interval,
      intervalFrequency,
      currency,
    ]
  }
  static func == (lhs: KnBillingPlan, rhs: KnBillingPlan) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnPaymentRequestStateContext: Hashable {
  var klarnaNetworkSessionToken: String? = nil
  var klarnaCustomer: KnCustomer? = nil
  var shipping: KnShipping? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnPaymentRequestStateContext? {
    let klarnaNetworkSessionToken: String? = nilOrValue(pigeonVar_list[0])
    let klarnaCustomer: KnCustomer? = nilOrValue(pigeonVar_list[1])
    let shipping: KnShipping? = nilOrValue(pigeonVar_list[2])

    return KnPaymentRequestStateContext(
      klarnaNetworkSessionToken: klarnaNetworkSessionToken,
      klarnaCustomer: klarnaCustomer,
      shipping: shipping
    )
  }
  func toList() -> [Any?] {
    return [
      klarnaNetworkSessionToken,
      klarnaCustomer,
      shipping,
    ]
  }
  static func == (lhs: KnPaymentRequestStateContext, rhs: KnPaymentRequestStateContext) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnCustomer: Hashable {
  var customerToken: String? = nil
  var customerTokenReference: String? = nil
  var customerProfile: KnCustomerProfile? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnCustomer? {
    let customerToken: String? = nilOrValue(pigeonVar_list[0])
    let customerTokenReference: String? = nilOrValue(pigeonVar_list[1])
    let customerProfile: KnCustomerProfile? = nilOrValue(pigeonVar_list[2])

    return KnCustomer(
      customerToken: customerToken,
      customerTokenReference: customerTokenReference,
      customerProfile: customerProfile
    )
  }
  func toList() -> [Any?] {
    return [
      customerToken,
      customerTokenReference,
      customerProfile,
    ]
  }
  static func == (lhs: KnCustomer, rhs: KnCustomer) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnCustomerProfile: Hashable {
  var address: KnAddress? = nil
  var customerId: String? = nil
  var country: String? = nil
  var email: String? = nil
  var emailVerified: Bool? = nil
  var familyName: String? = nil
  var givenName: String? = nil
  var locale: String? = nil
  var phone: String? = nil
  var phoneVerified: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnCustomerProfile? {
    let address: KnAddress? = nilOrValue(pigeonVar_list[0])
    let customerId: String? = nilOrValue(pigeonVar_list[1])
    let country: String? = nilOrValue(pigeonVar_list[2])
    let email: String? = nilOrValue(pigeonVar_list[3])
    let emailVerified: Bool? = nilOrValue(pigeonVar_list[4])
    let familyName: String? = nilOrValue(pigeonVar_list[5])
    let givenName: String? = nilOrValue(pigeonVar_list[6])
    let locale: String? = nilOrValue(pigeonVar_list[7])
    let phone: String? = nilOrValue(pigeonVar_list[8])
    let phoneVerified: Bool? = nilOrValue(pigeonVar_list[9])

    return KnCustomerProfile(
      address: address,
      customerId: customerId,
      country: country,
      email: email,
      emailVerified: emailVerified,
      familyName: familyName,
      givenName: givenName,
      locale: locale,
      phone: phone,
      phoneVerified: phoneVerified
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      customerId,
      country,
      email,
      emailVerified,
      familyName,
      givenName,
      locale,
      phone,
      phoneVerified,
    ]
  }
  static func == (lhs: KnCustomerProfile, rhs: KnCustomerProfile) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnPresentationData: Hashable {
  var currency: String
  var amount: Int64
  var intent: KnPresentationIntent? = nil
  var paymentProgramEnablementCodes: [String]? = nil
  var subscriptionBillingInterval: KnInterval? = nil
  var subscriptionBillingIntervalFrequency: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnPresentationData? {
    let currency = pigeonVar_list[0] as! String
    let amount = pigeonVar_list[1] as! Int64
    let intent: KnPresentationIntent? = nilOrValue(pigeonVar_list[2])
    let paymentProgramEnablementCodes: [String]? = nilOrValue(pigeonVar_list[3])
    let subscriptionBillingInterval: KnInterval? = nilOrValue(pigeonVar_list[4])
    let subscriptionBillingIntervalFrequency: Int64? = nilOrValue(pigeonVar_list[5])

    return KnPresentationData(
      currency: currency,
      amount: amount,
      intent: intent,
      paymentProgramEnablementCodes: paymentProgramEnablementCodes,
      subscriptionBillingInterval: subscriptionBillingInterval,
      subscriptionBillingIntervalFrequency: subscriptionBillingIntervalFrequency
    )
  }
  func toList() -> [Any?] {
    return [
      currency,
      amount,
      intent,
      paymentProgramEnablementCodes,
      subscriptionBillingInterval,
      subscriptionBillingIntervalFrequency,
    ]
  }
  static func == (lhs: KnPresentationData, rhs: KnPresentationData) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnPresentationContent: Hashable {
  var instruction: KnPresentationInstruction
  var paymentStatus: KnPresentationPaymentStatus? = nil
  var paymentOption: KnPresentationPaymentOption? = nil
  var savedPaymentOption: KnPresentationPaymentOption? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnPresentationContent? {
    let instruction = pigeonVar_list[0] as! KnPresentationInstruction
    let paymentStatus: KnPresentationPaymentStatus? = nilOrValue(pigeonVar_list[1])
    let paymentOption: KnPresentationPaymentOption? = nilOrValue(pigeonVar_list[2])
    let savedPaymentOption: KnPresentationPaymentOption? = nilOrValue(pigeonVar_list[3])

    return KnPresentationContent(
      instruction: instruction,
      paymentStatus: paymentStatus,
      paymentOption: paymentOption,
      savedPaymentOption: savedPaymentOption
    )
  }
  func toList() -> [Any?] {
    return [
      instruction,
      paymentStatus,
      paymentOption,
      savedPaymentOption,
    ]
  }
  static func == (lhs: KnPresentationContent, rhs: KnPresentationContent) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnPresentationPaymentOption: Hashable {
  var paymentOptionId: String
  var header: KnPresentationText? = nil
  var badge: KnPresentationText? = nil
  var subheader: KnPresentationText? = nil
  var message: KnPresentationText? = nil
  var terms: KnPresentationText? = nil
  var paymentButton: KnPresentationPaymentButton? = nil
  var icon: KnPresentationIcon? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnPresentationPaymentOption? {
    let paymentOptionId = pigeonVar_list[0] as! String
    let header: KnPresentationText? = nilOrValue(pigeonVar_list[1])
    let badge: KnPresentationText? = nilOrValue(pigeonVar_list[2])
    let subheader: KnPresentationText? = nilOrValue(pigeonVar_list[3])
    let message: KnPresentationText? = nilOrValue(pigeonVar_list[4])
    let terms: KnPresentationText? = nilOrValue(pigeonVar_list[5])
    let paymentButton: KnPresentationPaymentButton? = nilOrValue(pigeonVar_list[6])
    let icon: KnPresentationIcon? = nilOrValue(pigeonVar_list[7])

    return KnPresentationPaymentOption(
      paymentOptionId: paymentOptionId,
      header: header,
      badge: badge,
      subheader: subheader,
      message: message,
      terms: terms,
      paymentButton: paymentButton,
      icon: icon
    )
  }
  func toList() -> [Any?] {
    return [
      paymentOptionId,
      header,
      badge,
      subheader,
      message,
      terms,
      paymentButton,
      icon,
    ]
  }
  static func == (lhs: KnPresentationPaymentOption, rhs: KnPresentationPaymentOption) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnPresentationText: Hashable {
  var type: String
  var text: String? = nil
  var parts: [KnPresentationTextPart]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnPresentationText? {
    let type = pigeonVar_list[0] as! String
    let text: String? = nilOrValue(pigeonVar_list[1])
    let parts: [KnPresentationTextPart]? = nilOrValue(pigeonVar_list[2])

    return KnPresentationText(
      type: type,
      text: text,
      parts: parts
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      text,
      parts,
    ]
  }
  static func == (lhs: KnPresentationText, rhs: KnPresentationText) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnPresentationTextPart: Hashable {
  var type: String
  var text: String
  var url: String? = nil
  var context: KnPresentationTextPartLinkContext? = nil
  var styles: [KnPresentationTextPartStyle?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnPresentationTextPart? {
    let type = pigeonVar_list[0] as! String
    let text = pigeonVar_list[1] as! String
    let url: String? = nilOrValue(pigeonVar_list[2])
    let context: KnPresentationTextPartLinkContext? = nilOrValue(pigeonVar_list[3])
    let styles: [KnPresentationTextPartStyle?]? = nilOrValue(pigeonVar_list[4])

    return KnPresentationTextPart(
      type: type,
      text: text,
      url: url,
      context: context,
      styles: styles
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      text,
      url,
      context,
      styles,
    ]
  }
  static func == (lhs: KnPresentationTextPart, rhs: KnPresentationTextPart) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnPresentationPaymentButton: Hashable {
  var text: String
  var imageUrl: String? = nil
  var imageAlignment: KnPresentationImageAlignment? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnPresentationPaymentButton? {
    let text = pigeonVar_list[0] as! String
    let imageUrl: String? = nilOrValue(pigeonVar_list[1])
    let imageAlignment: KnPresentationImageAlignment? = nilOrValue(pigeonVar_list[2])

    return KnPresentationPaymentButton(
      text: text,
      imageUrl: imageUrl,
      imageAlignment: imageAlignment
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      imageUrl,
      imageAlignment,
    ]
  }
  static func == (lhs: KnPresentationPaymentButton, rhs: KnPresentationPaymentButton) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KnPresentationIcon: Hashable {
  var alt: String? = nil
  var badgeImageUrl: String? = nil
  var rectangleImageUrl: String? = nil
  var squareImageUrl: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KnPresentationIcon? {
    let alt: String? = nilOrValue(pigeonVar_list[0])
    let badgeImageUrl: String? = nilOrValue(pigeonVar_list[1])
    let rectangleImageUrl: String? = nilOrValue(pigeonVar_list[2])
    let squareImageUrl: String? = nilOrValue(pigeonVar_list[3])

    return KnPresentationIcon(
      alt: alt,
      badgeImageUrl: badgeImageUrl,
      rectangleImageUrl: rectangleImageUrl,
      squareImageUrl: squareImageUrl
    )
  }
  func toList() -> [Any?] {
    return [
      alt,
      badgeImageUrl,
      rectangleImageUrl,
      squareImageUrl,
    ]
  }
  static func == (lhs: KnPresentationIcon, rhs: KnPresentationIcon) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KnPaymentRequestState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KnPaymentRequestStateReason(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KnCollectCustomerProfileType(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KnRequestCustomerTokenScope(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KnShippingConfigMode(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KnShippingType(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KnShippingTypeAttribute(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KnInterval(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KnFreeTrial(rawValue: enumResultAsInt)
      }
      return nil
    case 138:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KnPresentationIntent(rawValue: enumResultAsInt)
      }
      return nil
    case 139:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KnPresentationInstruction(rawValue: enumResultAsInt)
      }
      return nil
    case 140:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KnPresentationPaymentStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 141:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KnPresentationImageAlignment(rawValue: enumResultAsInt)
      }
      return nil
    case 142:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KnPresentationTextPartStyle(rawValue: enumResultAsInt)
      }
      return nil
    case 143:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KnPresentationTextPartLinkContext(rawValue: enumResultAsInt)
      }
      return nil
    case 144:
      return KnPaymentRequestData.fromList(self.readValue() as! [Any?])
    case 145:
      return KnPaymentRequest.fromList(self.readValue() as! [Any?])
    case 146:
      return KnRequestCustomerToken.fromList(self.readValue() as! [Any?])
    case 147:
      return KnShippingConfig.fromList(self.readValue() as! [Any?])
    case 148:
      return KnSupplementaryPurchaseData.fromList(self.readValue() as! [Any?])
    case 149:
      return KnPartnerCustomer.fromList(self.readValue() as! [Any?])
    case 150:
      return KnAddress.fromList(self.readValue() as! [Any?])
    case 151:
      return KnLineItem.fromList(self.readValue() as! [Any?])
    case 152:
      return KnShipping.fromList(self.readValue() as! [Any?])
    case 153:
      return KnShippingRecipient.fromList(self.readValue() as! [Any?])
    case 154:
      return KnShippingOption.fromList(self.readValue() as! [Any?])
    case 155:
      return KnOndemandService.fromList(self.readValue() as! [Any?])
    case 156:
      return KnSubscription.fromList(self.readValue() as! [Any?])
    case 157:
      return KnBillingPlan.fromList(self.readValue() as! [Any?])
    case 158:
      return KnPaymentRequestStateContext.fromList(self.readValue() as! [Any?])
    case 159:
      return KnCustomer.fromList(self.readValue() as! [Any?])
    case 160:
      return KnCustomerProfile.fromList(self.readValue() as! [Any?])
    case 161:
      return KnPresentationData.fromList(self.readValue() as! [Any?])
    case 162:
      return KnPresentationContent.fromList(self.readValue() as! [Any?])
    case 163:
      return KnPresentationPaymentOption.fromList(self.readValue() as! [Any?])
    case 164:
      return KnPresentationText.fromList(self.readValue() as! [Any?])
    case 165:
      return KnPresentationTextPart.fromList(self.readValue() as! [Any?])
    case 166:
      return KnPresentationPaymentButton.fromList(self.readValue() as! [Any?])
    case 167:
      return KnPresentationIcon.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? KnPaymentRequestState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? KnPaymentRequestStateReason {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? KnCollectCustomerProfileType {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? KnRequestCustomerTokenScope {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? KnShippingConfigMode {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? KnShippingType {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? KnShippingTypeAttribute {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? KnInterval {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? KnFreeTrial {
      super.writeByte(137)
      super.writeValue(value.rawValue)
    } else if let value = value as? KnPresentationIntent {
      super.writeByte(138)
      super.writeValue(value.rawValue)
    } else if let value = value as? KnPresentationInstruction {
      super.writeByte(139)
      super.writeValue(value.rawValue)
    } else if let value = value as? KnPresentationPaymentStatus {
      super.writeByte(140)
      super.writeValue(value.rawValue)
    } else if let value = value as? KnPresentationImageAlignment {
      super.writeByte(141)
      super.writeValue(value.rawValue)
    } else if let value = value as? KnPresentationTextPartStyle {
      super.writeByte(142)
      super.writeValue(value.rawValue)
    } else if let value = value as? KnPresentationTextPartLinkContext {
      super.writeByte(143)
      super.writeValue(value.rawValue)
    } else if let value = value as? KnPaymentRequestData {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? KnPaymentRequest {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? KnRequestCustomerToken {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? KnShippingConfig {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? KnSupplementaryPurchaseData {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? KnPartnerCustomer {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? KnAddress {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? KnLineItem {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else if let value = value as? KnShipping {
      super.writeByte(152)
      super.writeValue(value.toList())
    } else if let value = value as? KnShippingRecipient {
      super.writeByte(153)
      super.writeValue(value.toList())
    } else if let value = value as? KnShippingOption {
      super.writeByte(154)
      super.writeValue(value.toList())
    } else if let value = value as? KnOndemandService {
      super.writeByte(155)
      super.writeValue(value.toList())
    } else if let value = value as? KnSubscription {
      super.writeByte(156)
      super.writeValue(value.toList())
    } else if let value = value as? KnBillingPlan {
      super.writeByte(157)
      super.writeValue(value.toList())
    } else if let value = value as? KnPaymentRequestStateContext {
      super.writeByte(158)
      super.writeValue(value.toList())
    } else if let value = value as? KnCustomer {
      super.writeByte(159)
      super.writeValue(value.toList())
    } else if let value = value as? KnCustomerProfile {
      super.writeByte(160)
      super.writeValue(value.toList())
    } else if let value = value as? KnPresentationData {
      super.writeByte(161)
      super.writeValue(value.toList())
    } else if let value = value as? KnPresentationContent {
      super.writeByte(162)
      super.writeValue(value.toList())
    } else if let value = value as? KnPresentationPaymentOption {
      super.writeByte(163)
      super.writeValue(value.toList())
    } else if let value = value as? KnPresentationText {
      super.writeByte(164)
      super.writeValue(value.toList())
    } else if let value = value as? KnPresentationTextPart {
      super.writeByte(165)
      super.writeValue(value.toList())
    } else if let value = value as? KnPresentationPaymentButton {
      super.writeByte(166)
      super.writeValue(value.toList())
    } else if let value = value as? KnPresentationIcon {
      super.writeByte(167)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol KnPaymentHostApi {
  func initiateWithId(instanceId: String, paymentRequestId: String, completion: @escaping (Result<KnPaymentRequest, Error>) -> Void)
  func initiateWithData(instanceId: String, data: KnPaymentRequestData, completion: @escaping (Result<KnPaymentRequest, Error>) -> Void)
  func fetch(instanceId: String, paymentRequestId: String, completion: @escaping (Result<KnPaymentRequest, Error>) -> Void)
  func cancel(instanceId: String, paymentRequestId: String, completion: @escaping (Result<KnPaymentRequest, Error>) -> Void)
  func presentationFetch(instanceId: String, data: KnPresentationData, completion: @escaping (Result<KnPresentationContent, Error>) -> Void)
  func presentationHandleLink(instanceId: String, url: String, completion: @escaping (Result<KnPresentationContent, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class KnPaymentHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `KnPaymentHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: KnPaymentHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initiateWithIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.klarna_network_payment.KnPaymentHostApi.initiateWithId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initiateWithIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let instanceIdArg = args[0] as! String
        let paymentRequestIdArg = args[1] as! String
        api.initiateWithId(instanceId: instanceIdArg, paymentRequestId: paymentRequestIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initiateWithIdChannel.setMessageHandler(nil)
    }
    let initiateWithDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.klarna_network_payment.KnPaymentHostApi.initiateWithData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initiateWithDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let instanceIdArg = args[0] as! String
        let dataArg = args[1] as! KnPaymentRequestData
        api.initiateWithData(instanceId: instanceIdArg, data: dataArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initiateWithDataChannel.setMessageHandler(nil)
    }
    let fetchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.klarna_network_payment.KnPaymentHostApi.fetch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fetchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let instanceIdArg = args[0] as! String
        let paymentRequestIdArg = args[1] as! String
        api.fetch(instanceId: instanceIdArg, paymentRequestId: paymentRequestIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      fetchChannel.setMessageHandler(nil)
    }
    let cancelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.klarna_network_payment.KnPaymentHostApi.cancel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let instanceIdArg = args[0] as! String
        let paymentRequestIdArg = args[1] as! String
        api.cancel(instanceId: instanceIdArg, paymentRequestId: paymentRequestIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelChannel.setMessageHandler(nil)
    }
    let presentationFetchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.klarna_network_payment.KnPaymentHostApi.presentationFetch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      presentationFetchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let instanceIdArg = args[0] as! String
        let dataArg = args[1] as! KnPresentationData
        api.presentationFetch(instanceId: instanceIdArg, data: dataArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      presentationFetchChannel.setMessageHandler(nil)
    }
    let presentationHandleLinkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.klarna_network_payment.KnPaymentHostApi.presentationHandleLink\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      presentationHandleLinkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let instanceIdArg = args[0] as! String
        let urlArg = args[1] as! String
        api.presentationHandleLink(instanceId: instanceIdArg, url: urlArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      presentationHandleLinkChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol KnPaymentFlutterApiProtocol {
  func onButtonPressed(viewId viewIdArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class KnPaymentFlutterApi: KnPaymentFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onButtonPressed(viewId viewIdArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.klarna_network_payment.KnPaymentFlutterApi.onButtonPressed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([viewIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
